import test from 'node:test';import assert from 'node:assert/strict';import {readFile,readdir} from 'node:fs/promises';import {PGlite} from './counts-support.mjs';
const owner='00000000-0000-4000-8000-000000000010',other='00000000-0000-4000-8000-000000000011',listId='00000000-0000-4000-8000-000000000020',countId='00000000-0000-4000-8000-000000000021';
const list={listId,title:'Rimesse',status:'open',deleted:false};
const count={countId,listId,category:'plants',title:'Barbera',varietyLabel:null,quantity:27,notes:'Riga 2\nDa rimpiazzare',field:null,deleted:false};
async function database(){const db=new PGlite();await db.exec(`CREATE ROLE anon;CREATE ROLE authenticated;CREATE ROLE service_role BYPASSRLS;CREATE SCHEMA auth;CREATE TABLE auth.users(id uuid primary key,is_anonymous boolean default false);CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql AS $$ SELECT nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;CREATE TABLE public.projects(id uuid primary key,owner_user_id uuid,environment text,name text,deleted_at timestamptz);CREATE TABLE public.project_fields(project_id uuid,owner_user_id uuid,client_field_id text,label text,deleted_at timestamptz);INSERT INTO auth.users VALUES ('${owner}',true),('${other}',false);`);const file=(await readdir(new URL('../supabase/migrations/',import.meta.url))).find(f=>f.endsWith('_counts_v1.sql'));assert.ok(file,'migration exists');await db.exec(await readFile(new URL('../supabase/migrations/'+file,import.meta.url),'utf8'));return db;}
async function apply(db,kind,value,revision=0,op=crypto.randomUUID(),who=owner,env='TEST'){return (await db.query('select public.counts_apply($1,$2,$3,$4,$5,$6::jsonb) as result',[who,env,op,kind,revision,JSON.stringify(value)])).rows[0].result;}
test('SQL ownership, CAS, operation idempotency and tombstones preserve counts',async()=>{const db=await database();try{
 const op=crypto.randomUUID();const one=await apply(db,'list',list,0,op);assert.equal(one.value.revision,1);assert.deepEqual(await apply(db,'list',list,0,op),one);
 await assert.rejects(apply(db,'list',{...list,title:'changed'},0,op),/VALIDATION_ERROR/);
 const entry=await apply(db,'count',count);assert.equal(entry.value.quantity,27);assert.equal(entry.value.revision,1);
 await assert.rejects(apply(db,'count',{...count,quantity:3},0),/VERSION_CONFLICT/);
 await assert.rejects(apply(db,'count',count,1,crypto.randomUUID(),other),/NOT_FOUND_OR_FORBIDDEN/);
 const deleted=await apply(db,'count',{...count,deleted:true},1);assert.equal(deleted.value.deleted,true);await assert.rejects(apply(db,'count',count,2),error=>{assert.match(error.message,/VERSION_CONFLICT/);assert.equal(JSON.parse(error.detail).current.deleted,true);return true;});
 await db.exec(`SET ROLE authenticated;SET request.jwt.claim.sub='${other}';`);assert.equal((await db.query('select * from counts_lists')).rows.length,0);
 await assert.rejects(db.query("update counts_lists set revision=999"),/permission denied/);await assert.rejects(apply(db,'list',list),/permission denied/);
 }finally{await db.close();}});
test('SQL rejects a foreign field without exposing field metadata and isolates environment',async()=>{const db=await database();try{await apply(db,'list',list);await db.query('insert into projects values ($1,$2,$3,$4,null)',[other,other,'TEST','Hidden']);await db.query('insert into project_fields values ($1,$2,$3,$4,null)',[other,other,'field-1','Hidden']);await assert.rejects(apply(db,'count',{...count,field:{projectId:other,fieldId:'field-1',projectLabel:'Hidden',fieldLabel:'Hidden',associationStatus:'verified'}}),/FIELD_UNAVAILABLE/);await assert.rejects(apply(db,'count',count,0,crypto.randomUUID(),owner,'LIVE'),/NOT_FOUND_OR_FORBIDDEN/);}finally{await db.close();}});
test('immutable request and delivery lease deduplicate retries and stop expired uncertain retries',async()=>{const db=await database();try{await apply(db,'list',list);const result=await apply(db,'count',count);const {deleted,...record}=result.value;const snapshot={listId,listTitle:list.title,entries:[record]};const contact={firstName:'Mario',lastName:'Rossi',phone:'12345',email:'test@example.com',companyName:''};const key=crypto.randomUUID();const accept=()=>db.query('select counts_accept_submission($1,$2,$3,$4::jsonb,$5::jsonb,$6,$7) as value',[owner,'TEST',key,JSON.stringify(snapshot),JSON.stringify(contact),'Messaggio','v1']);
 const first=(await accept()).rows[0].value;assert.equal(first.submissionId,key);assert.deepEqual((await accept()).rows[0].value,first);assert.equal(first.noticeVersion,'v1');assert.deepEqual((await db.query('select counts_accept_submission($1,$2,$3,$4::jsonb,$5::jsonb,$6,$7,$8) as value',[owner,'TEST',key,JSON.stringify(snapshot),JSON.stringify(contact),'Messaggio','v1','v2'])).rows[0].value,first);await assert.rejects(db.query('select counts_accept_submission($1,$2,$3,$4::jsonb,$5::jsonb,$6,$7,$8)',[owner,'TEST',crypto.randomUUID(),JSON.stringify(snapshot),JSON.stringify(contact),'Messaggio','v1','v2']),/NOTICE_REQUIRED/);
 await apply(db,'count',{...count,quantity:99},1);assert.equal((await accept()).rows[0].value.snapshot.entries[0].quantity,27);
 await assert.rejects(db.query('select counts_accept_submission($1,$2,$3,$4::jsonb,$5::jsonb,$6,$7)',[owner,'TEST',key,JSON.stringify(snapshot),JSON.stringify(contact),'Different','v1']),/VALIDATION_ERROR/);
 const claim=async()=> (await db.query('select counts_claim_delivery($1,$2,$3,$4::jsonb) as value',[owner,'TEST',key,JSON.stringify({subject:'Conteggi',text:'Frozen'})])).rows[0].value;
 assert.equal((await claim()).send,true);assert.equal((await claim()).send,false);
 await db.query("update counts_deliveries set first_attempt_at=now()-interval '25 hours',lease_until=now()-interval '1 second' where submission_id=$1",[key]);assert.equal((await claim()).state,'uncertain');
 }finally{await db.close();}});
test('private guest hook preserves one archive and cannot be called by authenticated clients',async()=>{const db=await database();try{await apply(db,'list',list);await apply(db,'count',count);await assert.rejects(db.query('select private.counts_transfer_after_verified_grant($1,$2,$3)',[owner,other,'TEST']),/AUTH_REQUIRED/);await db.exec(`SET request.jwt.claim.sub='${other}';`);await db.query('select private.counts_transfer_after_verified_grant($1,$2,$3)',[owner,other,'TEST']);assert.equal((await db.query('select owner_user_id from counts_lists')).rows[0].owner_user_id,other);assert.equal((await db.query('select owner_user_id from counts_entries')).rows[0].owner_user_id,other);assert.equal((await db.query('select count(*)::int as n from counts_lists')).rows[0].n,1);await db.exec('SET ROLE authenticated');await assert.rejects(db.query('select private.counts_transfer_after_verified_grant($1,$2,$3)',[owner,other,'TEST']),/permission denied/);}finally{await db.close();}});
