import test from 'node:test';import assert from 'node:assert/strict';import {parseHTML} from 'linkedom';import {IDBFactory,scope} from './counts-support.mjs';import {createCountsStore} from '../conteggi/store.js';import {createCountsGateway} from '../src/counts-client.js';import {mountCountsUI} from '../conteggi/ui.js';import {CountsError} from '../conteggi/model.js';
test('uncertain submission survives closing and reopening with the same frozen key and payload',async()=>{
 const {document,window}=parseHTML('<html><body><main id="counts-main"></main><p id="counts-status"></p><button id="retry-save" hidden></button></body></html>');const store=createCountsStore({indexedDB:new IDBFactory()}),listId=crypto.randomUUID(),countId=crypto.randomUUID();
 const list={listId,title:'Rimesse',status:'open',revision:1,localRevision:0,syncState:'synced',updatedAt:new Date().toISOString()};const count={listId,countId,category:'plants',title:'Barbera',quantity:27,varietyLabel:null,notes:'Filare 2',field:null,revision:1,localRevision:0,syncState:'synced',updatedAt:list.updatedAt};await store.mutate(scope(),s=>{s.lists[listId]=list;s.counts[countId]=count;s.notice='v1';});
 const sent=[];const gateway=createCountsGateway({store,scope:scope(),channel:false,transport:{request:async()=>({lists:[],counts:[]}),submit:async request=>{sent.push(structuredClone(request));throw new CountsError('SYNC_UNAVAILABLE','Esito non confermato');}}});
 const settings={document,window,gateway,route:{view:'list',listId},config:{submitEnabled:true,noticeVersion:'v1'},authService:{getState:()=>({firstName:'Mario',lastName:'Rossi',phone:'123',email:'test@example.com'})},feedback:{pulse(){}}};let ui=mountCountsUI(settings);await ui.ready;
 document.querySelector('[data-action="review"]').click();await ui.whenIdle();document.querySelector('[data-action="freeze-review"]').click();await ui.whenIdle();document.querySelector('[data-action="send"]').click();await ui.whenIdle();assert.equal(sent.length,1);assert.equal(document.querySelector('[data-action="edit-review"]'),null,'an uncertain request must retain its immutable payload');
 await ui.destroy();ui=mountCountsUI(settings);await ui.ready;document.querySelector('[data-action="review"]').click();await ui.whenIdle();assert.ok(document.querySelector('[data-action="send"]'),'the previous frozen review must be offered for an explicit retry');document.querySelector('[data-action="send"]').click();await ui.whenIdle();assert.deepEqual(sent[1],sent[0]);await ui.destroy();await gateway.destroy();
});
test('a definitive rejection can return to editing before a new reviewed request is built',async()=>{const {document,window}=parseHTML('<html><body><main id="counts-main"></main><p id="counts-status"></p></body></html>');const store=createCountsStore({indexedDB:new IDBFactory()}),listId=crypto.randomUUID(),countId=crypto.randomUUID();const list={listId,title:'Rimesse',status:'open',revision:1,localRevision:0,syncState:'synced',updatedAt:new Date().toISOString()},count={listId,countId,category:'plants',title:'Barbera',quantity:27,varietyLabel:null,notes:'',field:null,revision:1,localRevision:0,syncState:'synced',updatedAt:list.updatedAt};await store.mutate(scope(),s=>{s.lists[listId]=list;s.counts[countId]=count;s.notice='v1';});const gateway=createCountsGateway({store,scope:scope(),channel:false,transport:{request:async()=>({lists:[list],counts:[count]}),submit:async()=>{throw new CountsError('VERSION_CONFLICT','Dati cambiati');}}});const ui=mountCountsUI({document,window,gateway,route:{view:'list',listId},config:{submitEnabled:true,noticeVersion:'v1'},authService:{getState:()=>({firstName:'Mario',lastName:'Rossi',phone:'123',email:'test@example.com'})},feedback:{pulse(){}}});await ui.ready;document.querySelector('[data-action="review"]').click();await ui.whenIdle();document.querySelector('[data-action="freeze-review"]').click();await ui.whenIdle();document.querySelector('[data-action="send"]').click();await ui.whenIdle();assert.ok(document.querySelector('[data-action="edit-review"]'));document.querySelector('[data-action="edit-review"]').click();await ui.whenIdle();assert.ok(document.querySelector('#submission-form'));await ui.destroy();await gateway.destroy();});
