import test from 'node:test';import assert from 'node:assert/strict';import {IDBFactory,scope} from './counts-support.mjs';
const {createCountsGateway}=await import('../src/counts-client.js').catch(()=>({}));
const {createCountsStore}=await import('../conteggi/store.js').catch(()=>({}));
async function setup(transport=null){const store=createCountsStore({indexedDB:new IDBFactory()});const gateway=createCountsGateway({store,scope:scope(),transport,channel:false});const list=(await gateway.createList({title:'Rimesse'})).value;const count=(await gateway.createCount({listId:list.listId,category:'plants'})).value;return {gateway,store,list,count};}
test('rapid input, reopening and duplicate command keep every count exactly once',async()=>{
 const {gateway:g,store,list,count}=await setup();await Promise.all(Array.from({length:30},()=>g.changeQuantity(list.listId,count.countId,'increment')));await Promise.all(Array.from({length:3},()=>g.changeQuantity(list.listId,count.countId,'decrement')));
 let c=await g.getCount(list.listId,count.countId);assert.equal(c.quantity,27);
 const input={listId:list.listId,countId:count.countId,expectedRevision:c.revision,expectedLocalRevision:c.localRevision,operationId:crypto.randomUUID(),patch:{quantity:29}};
 await g.updateCount(input);await g.updateCount(input);assert.equal((await g.getCount(list.listId,count.countId)).quantity,29);
 await assert.rejects(g.updateCount({...input,patch:{quantity:30}}),e=>e.code==='VALIDATION_ERROR');
 await g.checkpoint({view:'counter',listId:list.listId,countId:count.countId});const second=createCountsGateway({store,scope:scope(),channel:false});assert.equal((await second.resume()).countId,count.countId);assert.equal((await second.getCount(list.listId,count.countId)).quantity,29);await g.destroy();await second.destroy();
});
test('two editors cannot silently overwrite the same local revision',async()=>{const {gateway:g,list,count}=await setup();const input={listId:list.listId,countId:count.countId,expectedRevision:0,expectedLocalRevision:0,operationId:crypto.randomUUID(),patch:{notes:'prima'}};await g.updateCount(input);await assert.rejects(g.updateCount({...input,operationId:crypto.randomUUID(),patch:{notes:'seconda'}}),e=>e.code==='VERSION_CONFLICT');await g.destroy();});
test('sync waits for notice and identity switch ignores an old in-flight result',async()=>{
 let release;const calls=[];const transport={async request(action,input){calls.push(action);if(action==='notice')return {};if(action==='pull')return {lists:[],counts:[],submissions:[]};return new Promise(resolve=>release=()=>resolve({value:{...input.value,revision:1}}));}};
 const {gateway:g,list,count}=await setup(transport);await g.sync();assert.equal(calls.length,0);await g.acceptNotice('test-notice');const pending=g.sync();while(!release)await new Promise(r=>setTimeout(r,1));await g.setScope(scope('account-b'));release();await pending;assert.equal((await g.listLists()).items.length,0);await g.setScope(scope());assert.equal((await g.getCount(list.listId,count.countId)).quantity,0);await g.destroy();
});
test('server conflict retains local proposal and allows explicit resolution',async()=>{
 const transport={async request(action,input){if(action==='notice')return {};if(action==='pull')return {lists:[],counts:[],submissions:[]};if(input.kind==='list')return {value:{...input.value,revision:1}};const error=new Error('conflict');error.code='VERSION_CONFLICT';error.details={current:{...input.value,quantity:99,revision:2}};throw error;}};
 const {gateway:g,list,count}=await setup(transport);await g.changeQuantity(list.listId,count.countId,'increment');await g.acceptNotice('v1');await g.sync();const c=await g.getCount(list.listId,count.countId);assert.equal(c.quantity,1);assert.equal(c.syncState,'conflict');assert.equal(c.conflict.remote.quantity,99);await g.resolveConflict('count',count.countId,'remote');assert.equal((await g.getCount(list.listId,count.countId)).quantity,99);await g.destroy();
});
test('refresh follows all pages without silently dropping older lists',async()=>{let pulls=0;const one={listId:crypto.randomUUID(),title:'Prima',status:'open',revision:1,updatedAt:new Date().toISOString()};const two={...one,listId:crypto.randomUUID(),title:'Seconda'};const g=createCountsGateway({store:createCountsStore({indexedDB:new IDBFactory()}),scope:scope(),channel:false,transport:{async request(action,input){if(action==='notice')return {};pulls++;return input.cursor?{lists:[two],counts:[],nextCursor:null}:{lists:[one],counts:[],nextCursor:{counts_lists:one.listId}};}}});await g.acceptNotice('v1');await g.refresh();assert.equal((await g.listLists()).items.length,2);assert.equal(pulls,2);await g.destroy();});
