import test from 'node:test';import assert from 'node:assert/strict';
const {createCountsHandler}=await import('../supabase/functions/_shared/counts-handler.js').catch(()=>({}));
const owner='00000000-0000-4000-8000-000000000010',listId='00000000-0000-4000-8000-000000000020';
const request=(action,input={},extra={})=>new Request('https://backend.test/counts',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer token'},body:JSON.stringify({action,input,environment:'TEST',...extra})});
const flags={sync:true,admin:true,submit:true,environment:'TEST',noticeVersion:'v1',allowedOrigins:['https://site.test']};
test('disabled, unauthenticated, stale admin and missing notice cannot collect or reveal notes',async()=>{let calls=0;const repository={hasNotice:async()=>false,pull:async()=>{calls++;return {};},admin:async()=>{calls++;return {};}};
 const factory=(settings,user,mode='api')=>createCountsHandler({flags:settings,authenticate:async()=>user,repository},mode);
 assert.equal((await factory({...flags,sync:false},{id:owner})(request('pull'))).status,503);
 assert.equal((await factory(flags,null)(request('pull'))).status,401);
 assert.equal((await factory(flags,{id:owner})(request('pull'))).status,403);
 assert.equal((await factory(flags,{id:owner,isAdmin:false},'admin')(request('listUserLists'))).status,403);
 assert.equal((await factory(flags,{id:owner,isAdmin:true,isAnonymous:true},'admin')(request('listUserLists'))).status,403);assert.equal(calls,0);
});
test('owner comes from verified token; forbidden fields and environment spoofing are rejected',async()=>{let params;const repository={hasNotice:async()=>true,apply:async input=>{params=input;return {value:input.value};}};const handler=createCountsHandler({flags,authenticate:async()=>({id:owner}),repository});
 const op={kind:'list',entityId:listId,operationId:crypto.randomUUID(),expectedRevision:0,value:{listId,title:'Rimesse',status:'open',deleted:false}};
 assert.equal((await handler(request('mutate',op))).status,200);assert.equal(params.owner,owner);
 assert.equal((await handler(request('mutate',{...op,value:{...op.value,owner_user_id:'other'}}))).status,400);
 assert.equal((await handler(request('pull',{}, {environment:'LIVE'}))).status,400);
});
test('optional submission distinguishes acceptance and provider acknowledgement without real email',async()=>{let sends=0,finishes=[];const submissionId=crypto.randomUUID();const accepted={submissionId,acceptedAt:'2026-10-02T10:00:00Z',snapshot:{listId,listTitle:'Rimesse',entries:[]},contact:{firstName:'A',lastName:'B',companyName:'',email:'test@example.com',phone:'123'},message:''};const repository={hasNotice:async()=>true,acceptSubmission:async()=>accepted,claimDelivery:async()=>({send:true,body:{subject:'Conteggi'}}),finishDelivery:async input=>finishes.push(input)};
 const handler=createCountsHandler({flags,authenticate:async()=>({id:owner}),repository,composeEmail:()=>({subject:'Conteggi'}),deliver:async()=>{sends++;return {id:'fake-provider-id'};}},'submit');
 const input={submissionId,snapshot:{listId,listTitle:'Rimesse',entries:[{countId:crypto.randomUUID(),listId,category:'plants',title:'Barbera',quantity:27,notes:'',varietyLabel:null,field:null,revision:1,updatedAt:'2026-10-02T10:00:00Z'}]},contact:accepted.contact,message:'',noticeVersion:'v1'};
 const response=await handler(request(undefined,input));const body=await response.json();assert.equal(response.status,200);assert.equal(body.emailState,'provider_accepted');assert.equal(body.deliveredAt,undefined);assert.equal(sends,1);assert.equal(finishes[0].state,'provider_accepted');
 const disabled=createCountsHandler({flags:{...flags,submit:false},authenticate:async()=>({id:owner}),repository,deliver:async()=>sends++},'submit');assert.equal((await disabled(request(undefined,input))).status,503);assert.equal(sends,1);
});
