import test from 'node:test';import assert from 'node:assert/strict';import {parseHTML} from 'linkedom';import {IDBFactory,scope} from './counts-support.mjs';import {createCountsGateway} from '../src/counts-client.js';import {createCountsStore} from '../conteggi/store.js';
const {mountCountsUI}=await import('../conteggi/ui.js').catch(()=>({}));
test('one click counts once, confirmation keeps the row, and active tool does not reset it',async()=>{
 const {document,window}=parseHTML('<html><body><main id="counts-main"></main><p id="counts-status"></p><button id="tools-trigger"></button><div id="tools-menu" hidden><button data-tool="counts"></button><a data-tool="configurator"></a></div></body></html>');
 const gateway=createCountsGateway({store:createCountsStore({indexedDB:new IDBFactory()}),scope:scope(),channel:false});const list=(await gateway.createList({title:'Rimesse'})).value;const count=(await gateway.createCount({listId:list.listId,category:'plants'})).value;
 const ui=mountCountsUI({document,window,gateway,route:{view:'counter',listId:list.listId,countId:count.countId},config:{configuratorBaseUrl:'https://example.test/',syncEnabled:false},feedback:{pulse(){}}});await ui.ready;
 for(let i=0;i<30;i++)document.querySelector('[data-action="increment"]').click();await ui.whenIdle();assert.equal(document.querySelector('#quantity-display').textContent,'30');
 document.querySelector('[data-tool="counts"]').click();await ui.whenIdle();assert.equal((await gateway.getCount(list.listId,count.countId)).quantity,30);
 document.querySelector('[data-action="confirm-count"]').click();await ui.whenIdle();assert.ok(document.querySelector('[data-action="open-count"]'));assert.equal((await gateway.getCount(list.listId,count.countId)).quantity,30);await ui.destroy();await gateway.destroy();
});
test('a failed checkpoint blocks leaving the tool and keeps the screen intact',async()=>{const {document,window}=parseHTML('<html><body><main id="counts-main"></main><p id="counts-status"></p></body></html>');const gateway=createCountsGateway({store:createCountsStore({indexedDB:new IDBFactory()}),scope:scope(),channel:false});const ui=mountCountsUI({document,window,gateway,route:{view:'lists'},config:{syncEnabled:false},feedback:{pulse(){}}});await ui.ready;gateway.checkpoint=async()=>{throw new Error('Storage unavailable');};await assert.rejects(ui.prepareExit());assert.ok(document.querySelector('[data-action="start"]'));await ui.destroy();await gateway.destroy();});
test('storage failure retains every queued tap until the user retries',async()=>{const {document,window}=parseHTML('<html><body><main id="counts-main"></main><p id="counts-status"></p><button id="retry-save" data-action="retry" hidden></button></body></html>');const gateway=createCountsGateway({store:createCountsStore({indexedDB:new IDBFactory()}),scope:scope(),channel:false});const list=(await gateway.createList({title:'Rimesse'})).value,count=(await gateway.createCount({listId:list.listId,category:'plants'})).value;const original=gateway.changeQuantity;let available=false;gateway.changeQuantity=(...args)=>{if(!available){const error=new Error('Disco pieno');error.code='LOCAL_STORAGE_FAILED';throw error;}return original(...args);};const ui=mountCountsUI({document,window,gateway,route:{view:'counter',listId:list.listId,countId:count.countId},config:{},feedback:{pulse(){}}});await ui.ready;for(let i=0;i<5;i++)document.querySelector('[data-action="increment"]').click();await ui.whenIdle();await assert.rejects(ui.prepareExit());available=true;document.querySelector('#retry-save').click();await ui.whenIdle();assert.equal((await gateway.getCount(list.listId,count.countId)).quantity,5);await ui.destroy();await gateway.destroy();});
