import test from 'node:test';import assert from 'node:assert/strict';import {createTerrainModel} from '../src/terrain-model.js';import {fromUTM} from '../src/coordinate-system.js';
const api=await import('../src/terrain-context-dem.js').catch(e=>{if(e.code==='ERR_MODULE_NOT_FOUND')return {};throw e;});
const geo=([x,y])=>fromUTM([500000+x,5000000+y],32632),geometry=[[-20,-20],[20,-20],[20,20],[-20,20],[-20,-20]].map(geo);
function input(){return {model:createTerrainModel({grid:{width:5,height:5,origin:[499900,5000100],step:[50,-50],values:Array.from({length:25},(_,i)=>100+(i%5-2)*5)}}),geometry};}
function compositor(value=input()){assert.equal(typeof api.createDisplayTerrainSampler,'function','composite DEM sampler is required');return api.createDisplayTerrainSampler(value);}
test('display composition preserves frozen heights across the whole field and merges into context outside support',()=>{const source=input(),before=JSON.stringify(source.model),display=compositor(source);for(const x of [-20,0,20])assert.ok(Math.abs(display.heightAt(geo([x,0]),10)-(100+x*.1))<1e-4);assert.ok(Math.abs(display.heightAt(geo([101,0]),10)-10)<1e-8);assert.ok(Math.abs(display.heightAt(geo([100,0]),10)-10)<1e-4);const edge=display.heightAt(geo([99.99,0]),10);assert.ok(Math.abs(edge-10)<.001,'boundary approaches context without vertical wall');assert.equal(JSON.stringify(source.model),before);});
test('context is never synthesized by clamping native edge heights into the distant world',()=>{const display=compositor();assert.equal(display.heightAt(geo([10000,0]),37),37);assert.equal(display.heightAt(geo([-10000,0]),-5),-5);assert.throws(()=>display.heightAt(geo([10000,0]),NaN),/quota|height|context/i);});
test('Terrarium tile compositing preserves contextual encoded pixels away from native field',()=>{assert.equal(typeof api.composeDisplayTile,'function');const bytes=new Uint8ClampedArray(16).fill(0);for(let i=0;i<16;i+=4){bytes[i]=128;bytes[i+1]=10;bytes[i+3]=255;}const display=compositor(),pixels=api.composeDisplayTile({z:0,x:0,y:0,size:2},display,()=>10);assert.deepEqual(pixels,bytes);});
test('invalid/no-collar field is rejected rather than concealing a hard DEM boundary',()=>{assert.equal(typeof api.createDisplayTerrainSampler,'function');const f=input();f.geometry=[[-100,-100],[100,-100],[100,100],[-100,100],[-100,-100]].map(geo);assert.throws(()=>api.createDisplayTerrainSampler(f),/support|raccord|copertura|collar/i);});

test('overscaled context samples the canonical provider tile and interpolates continuously across tile edges',async()=>{
 assert.equal(typeof api.createContextDEMClient,'function');const requested=[];
 const client=api.createContextDEMClient({source:{urlTemplate:'https://example.test/{z}/{x}/{y}.png',maxzoom:1},fetchImpl:async url=>{requested.push(url);const parts=url.match(/\/(\d+)\/(\d+)\/(\d+)\.png$/).slice(1).map(Number);return {ok:true,arrayBuffer:async()=>new Uint16Array(parts).buffer};},decodePixels:async bytes=>{const [,x]=new Uint16Array(bytes),rgba=new Uint8ClampedArray(256*256*4);for(let row=0;row<256;row++)for(let col=0;col<256;col++){const encoded=(32768+x*256+col)*256,index=(row*256+col)*4;rgba[index]=encoded>>>16;rgba[index+1]=(encoded>>>8)&255;rgba[index+2]=encoded&255;rgba[index+3]=255;}return rgba;}});
 const left=await client.samplerFor({z:2,x:1,y:1,size:256}),right=await client.samplerFor({z:2,x:2,y:1,size:256});assert.ok(Math.abs(left(.5,.3)-255.5)<1e-8);assert.ok(Math.abs(right(.5,.3)-255.5)<1e-8);assert.ok(requested.every(url=>url.includes('/1/')),'provider requests never use overscaled z2');const count=requested.length;await client.samplerFor({z:2,x:2,y:1,size:256});assert.equal(requested.length,count,'decoded context reused');client.destroy();await assert.rejects(client.getTile({z:1,x:0,y:0}),{name:'AbortError'});
});
test('context request failures remain failures instead of substituting flat sea-level terrain',async()=>{assert.equal(typeof api.createContextDEMClient,'function');const client=api.createContextDEMClient({fetchImpl:async()=>({ok:false,status:503}),decodePixels:async()=>assert.fail('must not decode failure')});await assert.rejects(client.getTile({z:15,x:16000,y:16000}),/503/);client.destroy();});
test('display worker client cancellation rejects pending tiles and destroys outstanding initialization',async()=>{
 assert.equal(typeof api.createTerrainDisplayClient,'function');const listeners=new Map(),sent=[];let terminated=0;const worker={addEventListener:(name,fn)=>listeners.set(name,fn),postMessage:data=>sent.push(data),terminate(){terminated++;}};
 const f=input(),client=api.createTerrainDisplayClient({...f,workerFactory:()=>worker}),signal=new AbortController(),pending=client.tile({z:17,x:1,y:1,signal:signal.signal});signal.abort();await assert.rejects(pending,{name:'AbortError'});assert.equal(sent.at(-1).type,'cancel');client.destroy();client.destroy();await assert.rejects(client.ready,{name:'AbortError'});assert.equal(terminated,1);await assert.rejects(client.tile({z:17,x:1,y:1}),{name:'AbortError'});
});
test('transparent missing context pixels fail instead of becoming a spurious minus32768m pit',async()=>{assert.equal(typeof api.createContextDEMClient,'function');const client=api.createContextDEMClient({fetchImpl:async()=>({ok:true,arrayBuffer:async()=>new ArrayBuffer(1)}),decodePixels:async()=>new Uint8ClampedArray(256*256*4)});await assert.rejects(client.getTile({z:15,x:16000,y:16000}),/copertura|pixel|context|contesto/i);client.destroy();});
test('unmodified canonical context tiles bypass resampling while field and overzoom tiles require composition',()=>{assert.equal(typeof api.canPassContextTile,'function');const display={mercatorBounds:[.51,.51,.6,.6]};assert.equal(api.canPassContextTile({z:1,x:0,y:0},display),true);assert.equal(api.canPassContextTile({z:1,x:1,y:1},display),false);assert.equal(api.canPassContextTile({z:16,x:1,y:1},display),false,'overscaled tile has no provider byte equivalent');});
test('composite attribution preserves the frozen DTM citation and license with safe text escaping',()=>{assert.equal(typeof api.displayTerrainAttribution,'function');const attribution=api.displayTerrainAttribution({model:{source:{citation:'Regione <DTM> & survey',license:'CC BY 4.0'}},contextSource:{attribution:'Context provider'}});assert.ok(attribution.includes('Regione &lt;DTM&gt; &amp; survey'));assert.ok(attribution.includes('CC BY 4.0'));assert.ok(attribution.includes('Context provider'));assert.ok(!attribution.includes('<DTM>'));});
test('aborting a queued context consumer removes its fetch without spending a network slot',async()=>{
 let finish;const gate=new Promise(resolve=>{finish=resolve;}),calls=[];const rgba=new Uint8ClampedArray(256*256*4);for(let i=0;i<rgba.length;i+=4){rgba[i]=128;rgba[i+3]=255;}
 const client=api.createContextDEMClient({concurrency:1,fetchImpl:async(url)=>{calls.push(url);if(calls.length===1)await gate;return {ok:true,arrayBuffer:async()=>new ArrayBuffer(1)};},decodePixels:async()=>rgba});
 const first=client.getTile({z:2,x:0,y:0}),controller=new AbortController(),second=client.getTile({z:2,x:1,y:0,signal:controller.signal});controller.abort();const rejected=assert.rejects(second,{name:'AbortError'});finish();await first;await rejected;await new Promise(resolve=>setImmediate(resolve));assert.equal(calls.length,1,'cancelled queued tile never fetches');client.destroy();
});
test('shared context fetch survives one cancelled consumer and aborts when its last consumer leaves',async()=>{
 let finish,fetchSignal;const gate=new Promise(resolve=>{finish=resolve;}),rgba=new Uint8ClampedArray(256*256*4);for(let i=0;i<rgba.length;i+=4){rgba[i]=128;rgba[i+3]=255;}let calls=0;
 const client=api.createContextDEMClient({fetchImpl:async(_url,{signal})=>{calls++;fetchSignal=signal;await gate;return {ok:true,arrayBuffer:async()=>new ArrayBuffer(1)};},decodePixels:async()=>rgba});
 const a=new AbortController(),b=new AbortController(),first=client.getTile({z:2,x:0,y:0,signal:a.signal}),second=client.getTile({z:2,x:0,y:0,signal:b.signal});a.abort();const rejected=assert.rejects(first,{name:'AbortError'});assert.equal(fetchSignal.aborted,false,'remaining consumer owns live fetch');finish();await second;await rejected;assert.equal(calls,1);client.destroy();
 const c=new AbortController();let abortedSignal;const retiring=api.createContextDEMClient({fetchImpl:(_url,{signal})=>new Promise((resolve,reject)=>{abortedSignal=signal;signal.addEventListener('abort',()=>reject(new DOMException('Aborted','AbortError')),{once:true});}),decodePixels:async()=>rgba});
 const only=retiring.getTile({z:2,x:0,y:0,signal:c.signal});c.abort();await assert.rejects(only,{name:'AbortError'});assert.equal(abortedSignal.aborted,true,'last consumer aborts inflight request');retiring.destroy();
});
test('context client destruction rejects every queued/active consumer and releases active fetch signals',async()=>{
 const signals=[],client=api.createContextDEMClient({concurrency:1,fetchImpl:(_url,{signal})=>{signals.push(signal);return new Promise(()=>{});},decodePixels:async()=>assert.fail('destroyed fetch must not decode')});
 const first=client.getTile({z:2,x:0,y:0}),second=client.getTile({z:2,x:1,y:0}),results=Promise.allSettled([first,second]);client.destroy();client.destroy();const retired=await results;assert.ok(retired.every(result=>result.status==='rejected'&&result.reason.name==='AbortError'));assert.equal(signals.length,1);assert.equal(signals[0].aborted,true);
});
test('retiring an unshared stuck fetch promptly frees its slot for a visible tile',async()=>{
 let calls=0;const rgba=new Uint8ClampedArray(256*256*4);for(let i=0;i<rgba.length;i+=4){rgba[i]=128;rgba[i+3]=255;}
 const client=api.createContextDEMClient({concurrency:1,fetchImpl:async()=>{if(++calls===1)return new Promise(()=>{});return {ok:true,arrayBuffer:async()=>new ArrayBuffer(1)};},decodePixels:async()=>rgba}),controller=new AbortController(),retired=client.getTile({z:2,x:0,y:0,signal:controller.signal}),visible=client.getTile({z:2,x:1,y:0});controller.abort();await assert.rejects(retired,{name:'AbortError'});
 let timer;try{await Promise.race([visible,new Promise((_,reject)=>{timer=setTimeout(()=>reject(new Error('cancelled fetch held the network slot')),100);})]);assert.equal(calls,2);}finally{clearTimeout(timer);client.destroy();}
});
