import test from 'node:test';import assert from 'node:assert/strict';import {parseHTML} from 'linkedom';import {createTerrainController} from '../src/terrain-controller.js';
const deferred=()=>{let resolve;const promise=new Promise(done=>resolve=done);return {promise,resolve};};
function fixture(extra={}){const {document}=parseHTML('<section id="terrain-card"></section>');let context={ownerId:'owner',fieldId:'field'},geometry=[[7,45],[7.001,45],[7,45.001],[7,45]];const states=[],model={contentHash:'native'};const api={map:{},gesturePolicy:{},stopTools(){}};const controller=createTerrainController({document,getProject:()=>({geometry}),getContext:()=>context,getMapApi:()=>api,summarize:async()=>({valid:true}),loadTerrain:async()=>model,onStateChange:state=>states.push(state),...extra});return {controller,states,document,model,api,setContext:value=>context=value,setGeometry:value=>geometry=value};}
test('common-map opening awaits automatic acquisition, emits available busy state and forwards gesture ownership',async()=>{
 const loading=deferred();let options,opens=0;const f=fixture({loadTerrain:()=>loading.promise,createMapView:async value=>{options=value;return {open:async()=>opens++,close(){},destroy(){}};}});const open=f.controller.toggle3D();assert.equal(f.controller.getState().viewOpening,true);loading.resolve(f.model);await open;assert.equal(opens,1);assert.equal(options.gesturePolicy,f.api.gesturePolicy);assert.equal(f.controller.getState().in3D,true);assert.ok(f.states.some(s=>s.available&&s.viewOpening));assert.equal(f.document.querySelector('[data-terrain="view"]'),null);f.controller.destroy();
});
test('a late automatic acquisition cannot open after field, account or explicit close',async()=>{
 for(const change of [f=>f.setContext({ownerId:'owner',fieldId:'other'}),f=>f.setContext({ownerId:'other',fieldId:'field'}),f=>f.controller.close3D()]){const loading=deferred();let creates=0;const f=fixture({loadTerrain:()=>loading.promise,createMapView:async()=>{creates++;return {open(){},destroy(){}};}});const open=f.controller.toggle3D();change(f);loading.resolve(f.model);await open;assert.equal(creates,0);assert.equal(f.controller.getState().in3D,false);f.controller.destroy();}
});
test('overview has no available 3D view or arbitrary model acquisition',async()=>{let loads=0;const f=fixture({loadTerrain:async()=>{loads++;return f.model;}});f.setContext({ownerId:'owner',fieldId:null});f.setGeometry(null);await f.controller.toggle3D();assert.equal(loads,0);assert.equal(f.controller.getState().available,false);f.controller.destroy();});
test('an asynchronous graphics error closes controller state through the view callback',async()=>{let options,closed=0;const f=fixture({createMapView:async value=>{options=value;return {open:async()=>{},close:()=>closed++,destroy(){}};}});await f.controller.toggle3D();assert.equal(typeof options.onError,'function');options.onError(new Error('graphics'));assert.equal(f.controller.getState().in3D,false);assert.ok(closed);assert.match(f.controller.getState().status,/graphics/);f.controller.destroy();});
test('destroy publishes unavailable state so the common map cannot reopen a disposed controller',async()=>{const f=fixture();await f.controller.refresh();assert.equal(f.states.at(-1).available,true);f.controller.destroy();assert.equal(f.states.at(-1).available,false);await f.controller.toggle3D();assert.equal(f.controller.getState().in3D,false);});
