import test from 'node:test';import assert from 'node:assert/strict';
const api=await import('../src/terrain-native-view.js').catch(e=>{if(e.code==='ERR_MODULE_NOT_FOUND')return {};throw e;});
const deferred=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b;});return {promise,resolve,reject};};
function setup(){
 const sources=new Map(),protocols=new Map(),listeners=new Map(),events=[],old={source:'existing',exaggeration:1.2};let terrain=old,camera={center:[9,45],zoom:17,pitch:0,bearing:4},destroyed=0;
 const map={getTerrain:()=>terrain,setTerrain(value){terrain=value;events.push(['terrain',value]);},addSource(id,spec){sources.set(id,spec);},removeSource(id){assert.notEqual(terrain?.source,id,'terrain released before source');sources.delete(id);},getSource:id=>sources.get(id),isSourceLoaded:()=>true,getCenter:()=>({lng:camera.center[0],lat:camera.center[1]}),getZoom:()=>camera.zoom,getPitch:()=>camera.pitch,getBearing:()=>camera.bearing,getPadding:()=>undefined,jumpTo(value){camera={...camera,...value};},stop(){},on(type,fn){if(!listeners.has(type))listeners.set(type,new Set());listeners.get(type).add(fn);},off(type,fn){listeners.get(type)?.delete(fn);},triggerRepaint(){}};
 const sdk={addProtocol:(id,fn)=>protocols.set(id,fn),removeProtocol:id=>protocols.delete(id)},client={ready:Promise.resolve({coordinate:[9.01,45.01],attribution:'Context fixture'}),tile:async request=>{if(request.signal?.aborted)throw new DOMException('Aborted','AbortError');return new Uint8Array([1,2,3]).buffer;},destroy(){destroyed++;}};
 const create=options=>{assert.equal(typeof api.createTerrainNativeView,'function','continuous native terrain view is required');return api.createTerrainNativeView({map,maplibre:sdk,model:{contentHash:'frozen'},geometry:[[9,45],[9.01,45],[9,45.01],[9,45]],displayClientFactory:()=>client,cameraControlsFactory:()=>({destroy(){}}),onSceneActive:(...args)=>events.push(['active',...args]),...options});};
 return {map,sdk,sources,protocols,events,client,create,old,camera:()=>camera,terrain:()=>terrain,destroyed:()=>destroyed,emit(type,event={}){for(const f of [...(listeners.get(type)??[])])f(event);}};
}
test('native view owns one global DEM source and restores prior terrain/camera once',async()=>{const f=setup(),before=f.camera(),view=f.create();await view.open();await view.open();assert.equal(f.sources.size,1);const [[id,spec]]=f.sources;assert.equal(spec.type,'raster-dem');assert.equal(spec.encoding,'terrarium');assert.equal(spec.bounds,undefined,'context must extend beyond field');assert.ok(spec.maxzoom>15,'local DTM needs finer display LOD than context provider');assert.deepEqual(f.terrain(),{source:id,exaggeration:1});assert.equal(f.protocols.size,1);assert.deepEqual(f.events.find(e=>e[0]==='active'),['active',true,null,{nativeTerrain:true}]);assert.deepEqual(new Uint8Array((await [...f.protocols.values()][0]({url:spec.tiles[0].replace('{z}','17').replace('{x}','1').replace('{y}','2')},new AbortController())).data),new Uint8Array([1,2,3]));f.map.jumpTo({pitch:75,center:[10,46]});view.close();view.close();assert.deepEqual(f.terrain(),f.old);assert.deepEqual(f.camera(),before);assert.equal(f.sources.size,0);assert.equal(f.protocols.size,0);assert.equal(f.destroyed(),1);view.destroy();});
test('closing a pending worker initialization promptly settles open and blocks stale activation',async()=>{const f=setup(),wait=deferred();f.client.ready=wait.promise;const view=f.create(),opening=view.open();view.close();await Promise.race([opening,new Promise((_,reject)=>setTimeout(()=>reject(new Error('open hung after close')),100))]);wait.resolve({coordinate:[9,45]});await Promise.resolve();assert.equal(f.sources.size,0);assert.equal(f.destroyed(),1);view.destroy();});
test('source failure rolls back owned native state and reports one error',async()=>{const f=setup(),errors=[],view=f.create({onError:e=>errors.push(e)});await view.open();const id=[...f.sources.keys()][0];f.emit('error',{sourceId:id,error:new Error('context unavailable')});await Promise.resolve();assert.deepEqual(f.terrain(),f.old);assert.equal(f.sources.size,0);assert.equal(f.protocols.size,0);assert.equal(errors.length,1);view.destroy();});
test('removed map releases worker and protocol without writing terrain or camera',async()=>{const f=setup(),view=f.create();await view.open();const before=f.events.length;f.map.setTerrain=()=>assert.fail('map already removed');f.map.jumpTo=()=>assert.fail('map already removed');f.map.removeSource=()=>assert.fail('style already removed');f.emit('remove');assert.equal(f.destroyed(),1);assert.equal(f.protocols.size,0);assert.equal(f.events.length,before);view.destroy();});
test('retired generation failure cannot close a reopened native view',async()=>{const f=setup(),view=f.create();await view.open();const handler=[...f.protocols.values()][0];view.close();await view.open();await assert.rejects(handler({url:'retired://17/1/2'},new AbortController()),/chiusa|closed|Abort/i);assert.equal(f.sources.size,1);view.destroy();});
test('native overlay preparation precedes terrain rendering and pending cancellation restores it without announcing readiness',async()=>{const f=setup(),statuses=[];f.map.isSourceLoaded=()=>false;let preparedBeforeTerrain=false;const set=f.map.setTerrain;f.map.setTerrain=value=>{if(value?.source?.startsWith('obice-terrain-dem-'))preparedBeforeTerrain=f.events.at(-1)?.[0]==='active'&&f.events.at(-1)?.[1]===true;set(value);};const view=f.create({onStatus:value=>statuses.push(value)}),opening=view.open();await Promise.resolve();await Promise.resolve();assert.equal(preparedBeforeTerrain,true,'editor layers must be suspended before first terrain render');assert.equal(f.sources.size,1);view.close();await opening;f.emit('sourcedata');assert.equal(f.sources.size,0);assert.deepEqual(f.events.filter(e=>e[0]==='active').map(e=>e[1]),[true,false]);assert.ok(!statuses.some(value=>value.startsWith('Terreno continuo')));assert.deepEqual(f.terrain(),f.old);view.destroy();});
test('style replacement releases owned protocol and worker without restoring a missing prior source',async()=>{const f=setup(),view=f.create({onError(){}});await view.open();f.sources.clear();f.map.setTerrain=value=>{assert.equal(value,null,'prior source was removed with style');};f.emit('styledata');await Promise.resolve();assert.equal(f.protocols.size,0);assert.equal(f.destroyed(),1);view.destroy();});
test('satellite failure retires native terrain instead of presenting an untextured continuous surface',async()=>{const f=setup(),errors=[],view=f.create({onError:error=>errors.push(error)});await view.open();f.emit('error',{sourceId:'satellite',error:new Error('satellite unavailable')});await Promise.resolve();assert.equal(f.sources.size,0);assert.deepEqual(f.terrain(),f.old);assert.equal(errors.length,1);view.destroy();});
