import test from 'node:test';import assert from 'node:assert/strict';
import {intersectsParcel,mergeAutomaticReferences,createCadastralCoordinator} from '../src/cadastral-auto.js';
import {parseParcelCollection,handleCadastralParcels} from '../supabase/functions/_shared/cadastral-parcels.js';
import {normalizeCadastralReferences} from '../src/cadastral-references.js';
const box=(a,b,c,d)=>[[a,b],[c,b],[c,d],[a,d],[a,b]];
test('parcel intersection covers crossing, containment, holes, and a touched boundary',()=>{const field=box(1,1,3,3);assert.ok(intersectsParcel(field,{polygons:[[box(0,0,4,4)]]}));assert.ok(intersectsParcel(field,{polygons:[[box(2,0,2.1,4)]]}));assert.ok(intersectsParcel(field,{polygons:[[box(3,1,4,2)]]}));assert.equal(intersectsParcel(field,{polygons:[[box(0,0,4,4),box(.5,.5,3.5,3.5)]]}),false);assert.equal(intersectsParcel(field,{polygons:[[box(4,4,5,5)]]}),false);});
test('manual corrections survive repeated lookup and automatic metadata survives field normalization',()=>{const existing=[{source:'manual',municipality:'Alba',sheet:'99',parcel:'corrected',lookupKey:'A124_0012_0.345'},{source:'automatic',municipality:'Alba',sheet:'12',parcel:'77',lookupKey:'old'}];const incoming=[{source:'automatic',municipality:'Alba',sheet:'12',parcel:'345',lookupKey:'A124_0012_0.345'},{source:'automatic',municipality:'Alba',sheet:'12',parcel:'10',lookupKey:'new'}];const result=mergeAutomaticReferences(existing,incoming);assert.equal(result.length,2);assert.equal(result[0].parcel,'corrected');assert.equal(normalizeCadastralReferences(result)[1].source,'automatic');});
test('a stale cadastral response cannot change a resized field; incomplete responses preserve previous data',async()=>{let field={id:'a',geometry:box(8,44,8.01,44.01),cadastralRefs:[]};let resolve;const applied=[];const coordinator=createCadastralCoordinator({getField:()=>field,resolve:()=>new Promise(r=>resolve=r),apply:refs=>applied.push(refs)});const pending=coordinator.refresh(field);field={...field,geometry:box(8,44,8.02,44.01)};resolve({complete:true,references:[{source:'automatic',municipality:'Alba',sheet:'1',parcel:'2'}]});await pending;assert.equal(applied.length,0);const incomplete=createCadastralCoordinator({getField:()=>field,resolve:async()=>({complete:false,references:[]}),apply:()=>applied.push('bad')});await incomplete.refresh(field);assert.equal(applied.length,0);});
test('WFS parser keeps polygon holes and fails closed on malformed or truncated members',()=>{const xml='<wfs:FeatureCollection numberMatched="1" numberReturned="1"><wfs:member><cp:CadastralParcel gml:id="parcel"><cp:nationalCadastralReference>A124_0012_0.345</cp:nationalCadastralReference><gml:Polygon srsName="urn:ogc:def:crs:EPSG::6706"><gml:exterior><gml:LinearRing><gml:posList>44 8 44 8.01 44.01 8.01 44.01 8 44 8</gml:posList></gml:LinearRing></gml:exterior><gml:interior><gml:LinearRing><gml:posList>44.002 8.002 44.002 8.003 44.003 8.003 44.002 8.002</gml:posList></gml:LinearRing></gml:interior></gml:Polygon></cp:CadastralParcel></wfs:member></wfs:FeatureCollection>';const result=parseParcelCollection(xml);assert.equal(result.parcels[0].polygons[0].length,2);assert.deepEqual(result.parcels[0].polygons[0][0][0],[8,44]);assert.throws(()=>parseParcelCollection(xml.replace('numberReturned="1"','numberReturned="2"')));assert.throws(()=>parseParcelCollection('<html>Unavailable</html>'));});
test('cadastral proxy requires configured public API key and geographic limits before upstream fetch',async()=>{let calls=0;const dependencies={allowedKeys:['public'],fetchImpl:async()=>{calls++;throw Error('bad')}};assert.equal((await handleCadastralParcels(new Request('https://local/?west=8&south=44&east=8.001&north=44.001'),dependencies)).status,401);assert.equal((await handleCadastralParcels(new Request('https://local/?west=0&south=0&east=100&north=90',{headers:{apikey:'public'}}),dependencies)).status,400);assert.equal(calls,0);});

test('clearing an automatic cadastral section saves the blank correction and retains lookup identity',async()=>{
 const {parseHTML}=await import('linkedom');const {createCadastralReferenceEditor}=await import('../src/cadastral-reference-editor.js');
 const {document,Event}=parseHTML('<div id="editor"></div>');let saved;
 const editor=createCadastralReferenceEditor({document,container:document.querySelector('#editor'),onChange:refs=>saved=refs});
 editor.render([{source:'automatic',municipality:'Alba',section:'A',sheet:'42',parcel:'1045',lookupKey:'original'}]);
 const input=document.querySelector('[name="section"]');input.value='';input.dispatchEvent(new Event('change',{bubbles:true}));
 assert.equal(saved[0].section,undefined);assert.equal(saved[0].source,'manual');assert.equal(saved[0].lookupKey,'original');
});
