import {CATEGORY_LABELS,CountsError,summarizeCounts,patchCount,validateCountPatch,quantityAfter} from './model.js';
import {scopeKey} from './store.js';
import {buildCountsUrl} from './navigation.js';
import {buildSubmission} from './submission.js';
export const NOTICE_TEXT='I conteggi e le note sincronizzati sono conservati sui sistemi Vivai Obice e consultabili dagli amministratori autorizzati, anche senza una richiesta di fornitura. Il pulsante “Trasmetti a Vivai Obice” serve a sottoporci volontariamente un riepilogo come richiesta.';
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const states={local:'Salvato sul dispositivo',pending:'Sincronizzazione in attesa',synced:'Sincronizzato',error:'Salvato sul dispositivo · sincronizzazione da riprovare',conflict:'Conflitto da risolvere'};
const emails={pending:'Richiesta conservata · email in attesa',sending:'Richiesta conservata · invio email in corso',provider_accepted:'Richiesta conservata · email accettata dal servizio di invio',failed:'Richiesta conservata · invio email non riuscito',uncertain:'Richiesta conservata · esito email non confermato'};
const button=(action,label,extra='')=>`<button type="button" data-action="${action}" ${extra}>${label}</button>`;
export function mountCountsUI({document=globalThis.document,window=globalThis.window,gateway,route={view:'lists'},config={},fieldDirectory=null,pendingFieldContext=null,varietyCatalog=[],authService=null,admin=null,feedback}){
 const main=document.querySelector('#counts-main'),status=document.querySelector('#counts-status');let currentRoute={...route},data=null,pending=Promise.resolve(),lastError=null,disposed=false,renderVersion=0,modal=null,restoreFocus=null,review=null,reviewEditable=true,failedTask=null,storageBlocked=false,projectedCount=null,scopeName=scopeKey(gateway.getScope());const failedTasks=[],scopeQueues=new Map();
 const message=(value,error=false)=>{if(status){status.textContent=String(value??'').replace(/^VALIDATION_ERROR:\s*/,'');status.classList.toggle('error',error);status.setAttribute('role',error?'alert':'status');}};
 function park(owner,fn){if(!owner)return;if(owner===scopeName){failedTasks.push(fn);storageBlocked=true;lastError=new CountsError('LOCAL_STORAGE_FAILED','Lavoro sospeso: riprova il salvataggio di questo profilo');const retry=document.querySelector('#retry-save');if(retry)retry.hidden=false;}else{const saved=scopeQueues.get(owner)??{route:{view:'lists'},tasks:[]};saved.tasks.push(fn);scopeQueues.set(owner,saved);}}
 function run(fn,recovery=false){const owner=scopeName,epoch=gateway.getEpoch();const next=pending.catch(()=>{}).then(async()=>{if(owner!==scopeName||epoch!==gateway.getEpoch()){park(owner,fn);return;}if(storageBlocked&&!recovery){failedTasks.push(fn);return;}const value=await fn();if(lastError?.code==='VALIDATION_ERROR'){lastError=null;message('Salvato sul dispositivo');}return value;});pending=next.catch(error=>{if(owner!==scopeName||epoch!==gateway.getEpoch()){park(owner,fn);return;}if(['LOCAL_STORAGE_FAILED','VALIDATION_ERROR'].includes(error.code))lastError=error;failedTask=fn;if(error.code==='LOCAL_STORAGE_FAILED'){storageBlocked=true;if(!recovery)failedTasks.push(fn);}message(error.message||'Operazione non riuscita',true);const retry=document.querySelector('#retry-save');if(retry)retry.hidden=false;});return next;}
 function show(html){closeModal();restoreFocus=document.activeElement;modal=document.createElement('div');modal.className='counts-modal';modal.innerHTML=`<section role="dialog" aria-modal="true" aria-labelledby="dialog-title" class="dialog-card">${html}<div class="dialog-actions">${button('close-modal','Chiudi')}</div></section>`;document.body.append(modal);modal.querySelector('input,button,textarea,select')?.focus();}
 function closeModal(){modal?.remove();modal=null;restoreFocus?.focus?.();}
 function progress(record){return `<span class="sync-state ${esc(record.syncState)}">${esc(states[record.syncState]??states.local)}</span>`;}
 async function checkpoint(){await gateway.checkpoint(currentRoute);const restored=await gateway.resume();if(JSON.stringify(restored)!==JSON.stringify(currentRoute))throw new CountsError('LOCAL_STORAGE_FAILED','Ripristino non verificato');}
 async function go(next){await checkpoint();currentRoute={...next};await checkpoint();if(window?.history?.replaceState&&window.location)window.history.replaceState(null,'',buildCountsUrl(config.countsBaseUrl??new URL('./',window.location.href).href,currentRoute));await render();}
 function recordRows(counts){return summarizeCounts(counts).filter(c=>c.items.length).map(group=>`<section class="category-section"><div class="section-head"><h3>${CATEGORY_LABELS[group.category]}</h3><span>${group.totalQuantity}</span></div><div class="count-rows">${group.items.map(c=>`<article class="count-row"><div><h4>${esc(c.title)}</h4><p class="field-label">${esc(c.field?(c.field.associationStatus==='unavailable'?'Campo non disponibile':c.field.fieldLabel):'Senza campo associato')}</p>${progress(c)}${c.notes?`<p class="notes">${esc(c.notes)}</p>`:''}</div><strong>${c.quantity}</strong>${button('open-count','Apri',`data-count-id="${c.countId}"`)}</article>`).join('')}</div></section>`).join('');}
 async function fieldOptions(){const pendingChoice=pendingFieldContext&&currentRoute.view==='new'&&!currentRoute.projectId?`<label><input type="checkbox" name="pendingLocal" checked> Collega alla bozza locale: ${esc(pendingFieldContext.fieldLabel)} · bozza (${esc(pendingFieldContext.projectLabel)})</label>`:'';if(!fieldDirectory)return `${pendingChoice}<p class="muted">Il collegamento ai campi sarà disponibile con la rubrica condivisa del configuratore.</p>`;const epoch=gateway.getEpoch(),projects=await fieldDirectory.listProjects();if(epoch!==gateway.getEpoch())throw new CountsError('AUTH_REQUIRED');return `${pendingChoice}<label>Progetto<select name="projectId"><option value="">Nessun campo</option>${projects.map(p=>`<option value="${esc(p.projectId)}" ${p.projectId===currentRoute.projectId?'selected':''}>${esc(p.projectLabel)}</option>`).join('')}</select></label><label>Campo<select name="fieldId"><option value="">Seleziona campo</option></select></label>`;}
 async function loadFields(root,projectId){const select=root.querySelector('[name="fieldId"]');if(!select)return;select.innerHTML='<option value="">Senza campo</option>';if(projectId){const epoch=gateway.getEpoch(),fields=await fieldDirectory.listFields(projectId);if(epoch!==gateway.getEpoch())throw new CountsError('AUTH_REQUIRED');select.innerHTML+=fields.map(f=>`<option value="${esc(f.fieldId)}" ${f.fieldId===currentRoute.fieldId?'selected':''}>${esc(f.fieldLabel)}</option>`).join('');}}
 function varietyOptions(value=''){return varietyCatalog.length?`<label>Vitigno (facoltativo)<select name="varietyLabel"><option value="">Titolo libero</option>${varietyCatalog.map(v=>typeof v==='string'?v:v.label).map(v=>`<option value="${esc(v)}" ${v===value?'selected':''}>${esc(v)}</option>`).join('')}</select></label>`:'';}
 async function render(){const version=++renderVersion;lastError=null;failedTask=null;
  if(currentRoute.view==='resume'){const saved=await gateway.resume();currentRoute=saved&&['counter','list','new','lists'].includes(saved.view)?saved:{view:'lists'};}
  if(['counter','list'].includes(currentRoute.view)){try{data=await gateway.getList(currentRoute.listId);if(currentRoute.view==='counter')data.count=await gateway.getCount(currentRoute.listId,currentRoute.countId);}catch(error){if(version===renderVersion){message(error.message,true);main.innerHTML=`<section class="card"><h2>Conteggio non disponibile</h2><p>Verifica il profilo e, se attiva, la sincronizzazione. Puoi tornare alle tue liste.</p>${button('back','Le mie liste')}</section>`;}return;}}
  let html;
  if(currentRoute.view==='lists'){
   const recovery=await gateway.listRecoveryProposals();const page=await gateway.listLists({...(currentRoute.projectId?{projectId:currentRoute.projectId}:{}),...(currentRoute.fieldId?{fieldId:currentRoute.fieldId}:{})});const resume=await gateway.resume();
   html=`<section class="intro"><p class="eyebrow">Rimesse, pali e appunti di campo</p><h2>I tuoi conteggi</h2><p>Conta in campo, conserva le note e ritrova ogni lista.</p><div class="actions">${button('start','Inizia un conteggio','class="primary"')}${button('create-list','Nuova lista')}${resume?.view==='counter'?button('resume','Riprendi il conteggio','class="resume"'):''}</div></section><section class="list-grid">${page.items.length?page.items.map(l=>`<article class="list-card"><span class="eyebrow">${l.status==='closed'?'Lista conclusa':'Lista aperta'}</span><h3>${esc(l.title)}</h3><p>${esc(new Date(l.updatedAt).toLocaleDateString('it-IT'))}</p>${progress(l)}${button('open-list','Apri lista',`data-list-id="${l.listId}"`)}</article>`).join(''):'<div class="empty"><h3>Un appunto alla volta.</h3><p>Inizia un conteggio o crea la tua prima lista.</p></div>'}</section>${recovery.length?`<section class="card"><h3>Proposte conservate</h3><p>Queste voci sono state eliminate sul server. I tuoi appunti restano disponibili qui.</p>${recovery.map(r=>`<h4>${esc(r.local.title)}</h4>${r.kind==='count'?`<p>Quantità: ${r.local.quantity}</p>`:''}<p class="notes">${esc(r.local.notes)}</p>`).join('')}</section>`:''}${page.nextCursor?button('more-lists','Altre liste',`data-cursor="${page.nextCursor}"`):''}`;
  }else if(currentRoute.view==='new'){
   html=`${button('back','← Liste')}<section class="card"><p class="eyebrow">Nuovo conteggio</p><h2>Cosa vuoi contare?</h2><form id="new-count-form"><label>Tipo<select name="category"><option value="plants">Piante da rimpiazzare</option><option value="posts">Pali da sostituire</option><option value="other">Altro</option></select></label><label>Titolo libero<input name="title" maxlength="200" placeholder="Es. Rimesse sul lato nord"></label>${varietyOptions()}${await fieldOptions()}<label>Note (facoltative)<textarea name="notes" maxlength="10000" rows="3" placeholder="Un appunto dal campo"></textarea></label>${button('create-count','Inizia a contare','class="primary"')}</form></section>`;
  }else if(currentRoute.view==='list'){
   const {list,counts}=data;const submissions=await gateway.listSubmissions(list.listId);
   html=`<div class="section-head">${button('back','← Liste')}<span>${list.status==='closed'?'Lista conclusa':'Lista aperta'}</span></div><section class="list-heading"><p class="eyebrow">Lista di campo</p><h2>${esc(list.title)}</h2>${progress(list)}<div class="actions">${button('add-count','Aggiungi conteggio','class="primary"')}${button('rename-list','Rinomina')}${button('toggle-list',list.status==='closed'?'Riapri lista':'Concludi lista')}${button('delete-list','Elimina','class="danger"')}</div></section>${counts.length?recordRows(counts):'<div class="empty">Questa lista è pronta per il primo conteggio.</div>'}${list.conflict?conflictHTML('list',list):''}${config.submitEnabled?`<aside class="submission-invite"><h3>${counts.some(c=>c.category==='plants')?'Vuoi parlarci delle tue rimesse?':'Vuoi segnalarci questi conteggi?'}</h3><p>Puoi trasmettere a Vivai Obice i conteggi che desideri sottoporci.</p>${button('review','Trasmetti a Vivai Obice')}<small>L’invio non costituisce un ordine.</small></aside>`:''}${submissions.map(s=>`<details class="card"><summary>Riepilogo trasmesso · ${esc(new Date(s.acceptedAt).toLocaleString('it-IT'))}</summary><p>${esc(emails[s.emailState]??emails.pending)}</p>${['pending','failed','uncertain','sending'].includes(s.emailState)?button('retry-submission','Riprova questa trasmissione',`data-id="${s.submissionId}"`):''}<p class="muted">Il ritentativo conserva lo stesso riepilogo e lo stesso identificatore.</p><h3>${esc(s.snapshot.listTitle)}</h3>${s.snapshot.entries.map(c=>`<p><b>${esc(c.title)} · ${c.quantity} ${CATEGORY_LABELS[c.category]}</b></p><p class="notes">${esc(c.notes)}</p>`).join('')}<p class="notes">${esc(s.message)}</p><p class="muted">Uno strumento Vivai Obice</p></details>`).join('')}`;
  }else if(currentRoute.view==='counter'){
   const c=data.count;html=`${button('to-list','← Riepilogo lista')}<section class="counter-card"><div class="section-head"><span class="eyebrow">${CATEGORY_LABELS[c.category]}</span>${progress(c)}</div><label class="count-title">Titolo<input name="title" value="${esc(c.title)}" maxlength="200" required></label>${varietyOptions(c.varietyLabel)}<p class="field-label">${esc(c.field?(c.field.associationStatus==='unavailable'?'Campo non disponibile':c.field.fieldLabel):'Senza campo associato')} ${button('change-field','Associa campo')}</p><output id="quantity-display" aria-label="Quantità" aria-live="off">${c.quantity}</output><div class="counter-buttons">${button('decrement','−1',`class="decrement" aria-label="Togli uno" ${c.quantity===0?'disabled':''}`)}${button('increment','+1','class="increment" aria-label="Aggiungi uno"')}</div><label class="manual">Correggi quantità<input name="quantity" value="${c.quantity}" inputmode="numeric" type="text" pattern="[0-9]+" aria-label="Correggi quantità"></label><label>Note<textarea name="notes" rows="3" maxlength="10000">${esc(c.notes)}</textarea></label><div class="feedback-options">${feedback?.capabilities?.sound?`<label><input type="checkbox" name="sound" ${feedback.getPreferences().sound?'checked':''}> Suono</label>`:''}${feedback?.capabilities?.haptic?`<label><input type="checkbox" name="haptic" ${feedback.getPreferences().haptic?'checked':''}> Vibrazione</label>`:''}<span>Ogni tocco vale una unità.</span></div>${c.conflict?conflictHTML('count',c):''}<div class="actions">${button('confirm-count','Conferma conteggio','class="primary"')}${button('delete-count','Elimina conteggio','class="danger"')}</div></section>`;
  }else if(currentRoute.view==='admin'){
   if(!config.adminEnabled||!admin)html='<section class="card"><h2>Conteggi utenti</h2><p>Consultazione amministrativa non attivata.</p></section>';
   else html=`${button('back','← I miei conteggi')}<section class="card"><h2>Conteggi utenti</h2><p>Gli appunti sincronizzati sono distinti dalle richieste trasmesse volontariamente.</p><form id="admin-filter"><label>Proprietario<select name="ownerKind"><option value="">Tutti</option><option value="guest">Guest</option><option value="user">Registrati</option></select></label><label>Dal<input name="from" type="date"></label><label>Al<input name="to" type="date"></label><label>Stato lista<select name="listStatus"><option value="">Tutte</option><option value="open">Aperta</option><option value="closed">Conclusa</option></select></label><label>Richiesta trasmessa<select name="hasSubmission"><option value="">Tutte</option><option value="true">Sì</option><option value="false">No</option></select></label><div class="actions">${button('admin-notes','Appunti sincronizzati')}${button('admin-submissions','Richieste trasmesse')}</div></form><div id="admin-results"></div></section>`;
  }
  if(version!==renderVersion||disposed)return;main.innerHTML=html??'';
  if(currentRoute.error)message(currentRoute.error,true);if(currentRoute.view==='new'&&fieldDirectory)await loadFields(main,currentRoute.projectId);
  if(currentRoute.view==='counter'){projectedCount=structuredClone(data.count);main.querySelector('[data-action="increment"]')?.focus();}else projectedCount=null;
 }
 function conflictHTML(kind,record){const remote=record.conflict?.remote;return `<aside class="conflict-panel"><h3>Due versioni da verificare</h3><p>La tua proposta è conservata.</p><h4>Su questo dispositivo</h4><p>${esc(record.title)}${kind==='count'?` · ${record.quantity}`:''}</p>${record.notes?`<p class="notes">${esc(record.notes)}</p>`:''}<h4>Versione ricevuta</h4>${remote?`<p>${esc(remote.title)}${kind==='count'?` · ${remote.quantity}`:''}${remote.deleted?' · eliminato':''}</p>${remote.notes?`<p class="notes">${esc(remote.notes)}</p>`:''}`:'<p>Versione non disponibile. Riprova la sincronizzazione.</p>'}${remote&&!remote.deleted?button('use-local','Mantieni la mia proposta',`data-kind="${kind}" data-id="${kind==='list'?record.listId:record.countId}"`):''}${remote?button('use-remote',remote.deleted?'Accetta eliminazione e conserva gli appunti':'Usa la versione ricevuta',`data-kind="${kind}" data-id="${kind==='list'?record.listId:record.countId}"`):''}${kind==='count'&&record.conflict?.code==='FIELD_UNAVAILABLE'?button('unassociate','Conserva senza associazione al campo',`data-kind="count" data-id="${record.countId}"`):''}</aside>`;}
 function patchContext(patch){const clean=validateCountPatch(patch),base=projectedCount??data.count;const context={owner:scopeName,route:{view:'counter',listId:base.listId,countId:base.countId},operationId:crypto.randomUUID(),expectedLocalRevision:base.localRevision};projectedCount=patchCount(base,clean);return context;}
 async function savePatch(patch,context=patchContext(patch)){if(context.owner!==scopeName)throw new CountsError('AUTH_REQUIRED');const epoch=gateway.getEpoch(),{listId,countId}=context.route,current=await gateway.getCount(listId,countId);context.input??={listId,countId,expectedRevision:current.revision,expectedLocalRevision:context.expectedLocalRevision,operationId:context.operationId,patch};try{const result=await gateway.updateCount(context.input);if(epoch!==gateway.getEpoch())throw new CountsError('AUTH_REQUIRED');data.count=await gateway.getCount(listId,countId);message(states[result.syncState]);}catch(error){if(error.code==='VERSION_CONFLICT'&&epoch===gateway.getEpoch()){const remote=current.conflict?.remote??error.details?.current??current;const proposal=patchCount(current,patch);data.count=await gateway.retainConflictProposal('count',countId,proposal,remote);await render();}throw error;}}
 function showFrozenReview(){const {snapshot,contact,message}=review;show(`<h2 id="dialog-title">Il riepilogo che trasmetterai</h2><p>Questo riepilogo è conservato. La trasmissione richiede una tua conferma.</p><h3>${esc(snapshot.listTitle)}</h3>${snapshot.entries.map(c=>`<p><b>${esc(c.title)} · ${c.quantity} ${CATEGORY_LABELS[c.category]}</b></p><p class="notes">${esc(c.notes)}</p><p>${esc(c.field?.fieldLabel??'Senza campo')}</p>`).join('')}<p>${esc(contact.firstName)} ${esc(contact.lastName)} · ${esc(contact.email)} · ${esc(contact.phone)}</p><p class="notes">${esc(message)}</p><p>L’invio non costituisce un ordine.</p>${reviewEditable?button('edit-review','Modifica il riepilogo'):''}${button('send','Conferma e trasmetti','class="primary"')}`);}
 async function reviewForm(){const profile=authService?.getState?.()??{};const draft=await gateway.getSubmissionDraft(data.list.listId);if(draft?.review){review=draft.review;reviewEditable=!draft.attemptState||draft.attemptState==='rejected';showFrozenReview();return;}show(`<h2 id="dialog-title">Rivedi prima di trasmettere</h2><p>L’invio non costituisce un ordine.</p><form id="submission-form"><div class="review-rows">${data.counts.map(c=>`<label><input name="selected" type="checkbox" value="${c.countId}" ${!draft?.selectedIds||draft.selectedIds.includes(c.countId)?'checked':''}><span>${esc(c.title)} · ${c.quantity} ${CATEGORY_LABELS[c.category]}<small class="notes">${esc(c.notes)}</small><small>${esc(c.field?.fieldLabel??'Senza campo')}</small></span></label>`).join('')}</div>${[['firstName','Nome','given-name'],['lastName','Cognome','family-name'],['phone','Telefono','tel'],['email','E-mail','email'],['companyName','Azienda (facoltativo)','organization']].map(([key,label,autocomplete])=>`<label>${label}<input name="${key}" type="${key==='email'?'email':key==='phone'?'tel':'text'}" autocomplete="${autocomplete}" value="${esc(draft?.contact?.[key]??profile[key]??'')}" ${key==='companyName'?'':'required'} maxlength="${key==='email'?254:key==='phone'?32:160}"></label>`).join('')}<label>Messaggio (facoltativo)<textarea name="message" maxlength="5000" rows="3">${esc(draft?.message??'')}</textarea></label><p><a href="https://www.vivaiobice.com/privacypolicy" target="_blank" rel="noopener">Informativa privacy</a></p>${button('freeze-review','Rivedi riepilogo','class="primary"')}</form>`);}
 async function adminResults(kind,cursor){const form=main.querySelector('#admin-filter');const input={};for(const key of ['ownerKind','from','to',...(kind==='notes'?['listStatus','hasSubmission']:[])]){const value=form.querySelector(`[name="${key}"]`)?.value;if(value)input[key]=key==='hasSubmission'?value==='true':key==='to'?value+'T23:59:59.999Z':value;}if(cursor)input.cursor=cursor;const epoch=gateway.getEpoch(),result=await (kind==='notes'?admin.listUserLists(input):admin.listSubmissions(input));if(epoch!==gateway.getEpoch())throw new CountsError('AUTH_REQUIRED');main.querySelector('#admin-results').innerHTML=`<h3>${kind==='notes'?'Appunti sincronizzati':'Richieste trasmesse'}</h3>${result.items.map(row=>`<article class="count-row"><div><h4>${esc(row.title??row.listTitle)}</h4><p>${row.owner.kind==='guest'?'Guest':'Registrato'} · ${esc(row.owner.technicalId)}</p><p>${esc(row.emailState?emails[row.emailState]:row.hasSubmission?'Richiesta presente':'Nessuna richiesta trasmessa')}</p></div>${button(kind==='notes'?'admin-open-list':'admin-open-submission','Consulta',`data-id="${row.listId??row.submissionId}"`)}</article>`).join('')||'<p>Nessun risultato.</p>'}${result.nextCursor?button('admin-more','Altri risultati',`data-kind="${kind}" data-cursor="${result.nextCursor}"`):''}`;}
 function actionContext(target){const name=target.dataset.action;const context={owner:scopeName,route:{...currentRoute},operationId:crypto.randomUUID(),listOperationId:crypto.randomUUID(),newListId:crypto.randomUUID(),newCountId:crypto.randomUUID(),listTitle:modal?.querySelector('[name="listTitle"]')?.value,expectedLocalRevision:name.includes('count')?data?.count?.localRevision:data?.list?.localRevision};if(name==='start')context.listTitle=`Conteggi del ${new Date().toLocaleDateString('it-IT')}`;if(name==='create-count'){context.listTitle=`Conteggi del ${new Date().toLocaleDateString('it-IT')}`;const form=main.querySelector('#new-count-form');context.form=Object.fromEntries(['category','title','varietyLabel','notes','projectId','fieldId'].map(k=>[k,form.querySelector(`[name="${k}"]`)?.value??'']));context.form.pendingLocal=form.querySelector('[name="pendingLocal"]')?.checked??false;}return context;}
 async function action(target,context=actionContext(target)){if(context.owner!==scopeName)throw new CountsError('AUTH_REQUIRED');const epoch=gateway.getEpoch(),valid=()=>{if(epoch!==gateway.getEpoch())throw new CountsError('AUTH_REQUIRED');};const name=target.dataset.action;
  if(name==='close-modal'){closeModal();return;}
  if(name==='retry'){if(storageBlocked){while(failedTasks.length){await failedTasks[0]();failedTasks.shift();}storageBlocked=false;lastError=null;failedTask=null;}else if(failedTask){const retry=failedTask;lastError=null;failedTask=null;await retry();}message('Operazione completata');if(document.querySelector('#retry-save'))document.querySelector('#retry-save').hidden=true;return;}
  if(name==='start'||name==='create-list'){const title=name==='start'?context.listTitle:null;if(title){const result=await gateway.createList({title,listId:context.newListId,operationId:context.listOperationId});valid();await go({view:'new',listId:result.value.listId});}else show(`<h2 id="dialog-title">Nuova lista</h2><label>Nome lista<input name="listTitle" maxlength="200" required></label>${button('save-new-list','Crea lista','class="primary"')}`);}
  if(name==='save-new-list'){const result=await gateway.createList({title:context.listTitle,listId:context.newListId,operationId:context.listOperationId});valid();closeModal();await go({view:'list',listId:result.value.listId});}
  if(name==='open-list')await go({view:'list',listId:target.dataset.listId});
  if(name==='more-lists'){const recovery=await gateway.listRecoveryProposals();const page=await gateway.listLists({cursor:target.dataset.cursor,...(currentRoute.projectId?{projectId:currentRoute.projectId}:{}),...(currentRoute.fieldId?{fieldId:currentRoute.fieldId}:{})});for(const l of page.items){const article=document.createElement('article');article.className='list-card';article.innerHTML=`<h3>${esc(l.title)}</h3>${progress(l)}${button('open-list','Apri lista',`data-list-id="${l.listId}"`)}`;main.querySelector('.list-grid').append(article);}if(page.nextCursor)target.dataset.cursor=page.nextCursor;else target.remove();}
  if(name==='open-count')await go({view:'counter',listId:data.list.listId,countId:target.dataset.countId});
  if(name==='resume'){const saved=await gateway.resume();if(saved)await go(saved);}
  if(name==='back')await go({view:'lists'});
  if(name==='to-list'||name==='confirm-count')await go({view:'list',listId:currentRoute.listId});
  if(name==='add-count')await go({view:'new',listId:data.list.listId});
  if(name==='create-count'){const form=context.form;context.field??=form.fieldId?await fieldDirectory.resolveField(form.projectId,form.fieldId):form.pendingLocal&&pendingFieldContext?{projectId:null,fieldId:null,projectLabel:pendingFieldContext.projectLabel,fieldLabel:pendingFieldContext.fieldLabel,varietyLabel:pendingFieldContext.varietyLabel,associationStatus:'pending',localRef:{localProjectId:pendingFieldContext.localProjectId,localFieldId:pendingFieldContext.localFieldId}}:null;valid();if(form.fieldId&&!context.field)throw new CountsError('FIELD_UNAVAILABLE');const listId=context.route.listId??context.newListId;if(!context.route.listId)await gateway.createList({title:context.listTitle,listId,operationId:context.listOperationId});valid();const title=form.title.trim(),varietyLabel=form.varietyLabel||null;const result=await gateway.createCount({listId,countId:context.newCountId,operationId:context.operationId,category:form.category,...(title||varietyLabel?{title:title||varietyLabel}:{}),varietyLabel,notes:form.notes,field:context.field});valid();await go({view:'counter',listId,countId:result.value.countId});}
  if(name==='increment'||name==='decrement'){const result=await gateway.changeQuantity(context.route.listId,context.route.countId,name,undefined,context.operationId);valid();if(currentRoute.countId===context.route.countId){data.count=await gateway.getCount(context.route.listId,context.route.countId);main.querySelector('#quantity-display').textContent=data.count.quantity;main.querySelector('[name="quantity"]').value=data.count.quantity;main.querySelector('[data-action="decrement"]').disabled=data.count.quantity===0;}message(states[result.syncState]);}
  if(name==='rename-list')show(`<h2 id="dialog-title">Rinomina lista</h2><label>Nome lista<input name="listTitle" value="${esc(data.list.title)}" maxlength="200" required></label>${button('save-list-title','Salva','class="primary"')}`);
  if(name==='save-list-title'||name==='toggle-list'){const l=data.list;context.updateInput??={listId:context.route.listId,expectedRevision:l.revision,expectedLocalRevision:context.expectedLocalRevision,operationId:context.operationId,patch:name==='toggle-list'?{status:l.status==='closed'?'open':'closed'}:{title:context.listTitle}};await gateway.updateList(context.updateInput);valid();closeModal();await render();}
  if(name==='delete-list'||name==='delete-count')show(`<h2 id="dialog-title">Eliminare ${name==='delete-list'?'questa lista e i suoi conteggi':'questo conteggio'}?</h2><p>Conferma l’eliminazione.</p>${button(name==='delete-list'?'confirm-delete-list':'confirm-delete-count','Elimina','class="danger"')}`);
  if(name==='confirm-delete-list'){await gateway.deleteList(context.route.listId,context.expectedLocalRevision,context.operationId);valid();closeModal();await go({view:'lists'});}
  if(name==='confirm-delete-count'){await gateway.deleteCount(context.route.listId,context.route.countId,context.expectedLocalRevision,context.operationId);valid();closeModal();await go({view:'list',listId:context.route.listId});}
  if(name==='change-field'){const options=await fieldOptions();valid();show(`<h2 id="dialog-title">Associa a un campo</h2>${options}${button('save-field','Salva associazione')}`);if(fieldDirectory)await loadFields(modal,currentRoute.projectId);}
  if(name==='save-field'){if(!fieldDirectory){closeModal();return;}const projectId=modal.querySelector('[name="projectId"]').value,fieldId=modal.querySelector('[name="fieldId"]').value;const field=fieldId?await fieldDirectory.resolveField(projectId,fieldId):null;valid();if(fieldId&&!field)throw new CountsError('FIELD_UNAVAILABLE');await savePatch({field});closeModal();await render();}
  if(['use-local','use-remote','unassociate'].includes(name)){await gateway.resolveConflict(target.dataset.kind,target.dataset.id,name==='use-local'?'local':name==='unassociate'?'unassociate':'remote');valid();await render();}
  if(name==='sync'){await gateway.refresh();await render();message('Sincronizzazione verificata');}
  if(name==='notice')show(`<h2 id="dialog-title">Prima di sincronizzare</h2><p>${NOTICE_TEXT}</p><p>La sincronizzazione conserva gli appunti. La trasmissione di una richiesta richiede una tua scelta separata.</p><p><a href="https://www.vivaiobice.com/privacypolicy" target="_blank" rel="noopener">Informativa privacy</a></p>${button('accept-notice','Ho letto, attiva la sincronizzazione','class="primary"')}`);
  if(name==='accept-notice'){await gateway.acceptNotice(config.noticeVersion);closeModal();await gateway.refresh();await render();message('Sincronizzazione attivata');}
  if(name==='review')await reviewForm();
  if(name==='edit-review'){const draft=await gateway.getSubmissionDraft(context.route.listId);if(draft?.attemptState==='uncertain')throw new CountsError('VERSION_CONFLICT','L’esito è da verificare: ritenta lo stesso riepilogo');await gateway.saveSubmissionDraft({contact:draft?.contact??review.contact,message:draft?.message??review.message,selectedIds:draft?.selectedIds??review.snapshot.entries.map(c=>c.countId)},context.route.listId);await gateway.refresh();valid();data=await gateway.getList(context.route.listId);review=null;await reviewForm();}
  if(name==='freeze-review'){const form=modal.querySelector('#submission-form');if(form.reportValidity&&!form.reportValidity())return;context.draft??={contact:Object.fromEntries(['firstName','lastName','phone','email','companyName'].map(k=>[k,form.querySelector(`[name="${k}"]`).value.trim()])),message:form.querySelector('[name="message"]').value,selectedIds:[...form.querySelectorAll('[name="selected"]:checked')].map(n=>n.value)};const draft=context.draft;await gateway.saveSubmissionDraft(draft,context.route.listId);await gateway.sync();valid();const latest=await gateway.getList(context.route.listId);context.review??=buildSubmission({list:latest.list,counts:latest.counts.filter(c=>draft.selectedIds.includes(c.countId)),contact:draft.contact,message:draft.message,noticeVersion:config.noticeVersion});review=context.review;await gateway.saveSubmissionDraft({...draft,review},context.route.listId);valid();reviewEditable=true;showFrozenReview();}
  if(name==='send'){target.disabled=true;context.review??=structuredClone(review);try{await gateway.submit(context.review);valid();closeModal();await render();message('Riepilogo trasmesso e conservato');}catch(error){valid();const draft=await gateway.getSubmissionDraft(context.route.listId);reviewEditable=draft?.attemptState==='rejected';showFrozenReview();throw error;}finally{target.disabled=false;}}
  if(name==='retry-submission'){await gateway.retrySubmission(target.dataset.id);valid();await render();message('Ritentativo conservato con lo stesso riepilogo');}
  if(name==='admin-notes'||name==='admin-submissions')await adminResults(name==='admin-notes'?'notes':'submissions');
  if(name==='admin-more')await adminResults(target.dataset.kind,target.dataset.cursor);
  if(name==='admin-open-list'){const result=await admin.getUserList(target.dataset.id);valid();show(`<h2 id="dialog-title">Appunti sincronizzati</h2><h3>${esc(result.list.title)}</h3><p>${esc(result.owner.kind)} · ${esc(result.owner.technicalId)}</p>${result.counts.map(c=>`<p><b>${esc(c.title)} · ${c.quantity} ${CATEGORY_LABELS[c.category]}</b></p><p class="notes">${esc(c.notes)}</p>`).join('')}`);}
  if(name==='admin-open-submission'){const s=await admin.getSubmission(target.dataset.id);valid();show(`<h2 id="dialog-title">Richiesta trasmessa volontariamente</h2><p>${esc(emails[s.emailState])}</p>${s.snapshot.entries.map(c=>`<p><b>${esc(c.title)} · ${c.quantity}</b></p><p class="notes">${esc(c.notes)}</p>`).join('')}<p>${esc(s.contact.firstName)} ${esc(s.contact.lastName)} · ${esc(s.contact.email)}</p><p class="notes">${esc(s.message)}</p>`);}
 }
 function click(event){const tool=event.target.closest?.('[data-tool]');if(tool){event.preventDefault();if(tool.dataset.tool==='counts'){document.querySelector('#tools-menu').hidden=true;return;}void run(async()=>{if(lastError||storageBlocked)throw lastError;await checkpoint();window.location.assign(config.configuratorBaseUrl);}).catch(()=>{});return;}const target=event.target.closest?.('[data-action]');if(!target)return;event.preventDefault();if(target.dataset.action==='increment'||target.dataset.action==='decrement'){feedback?.pulse();main.querySelector('#quantity-display')?.classList.remove('pulse');window?.requestAnimationFrame?.(()=>main.querySelector('#quantity-display')?.classList.add('pulse'));}let context;try{context=actionContext(target);if(['increment','decrement'].includes(target.dataset.action)&&projectedCount)projectedCount=patchCount(projectedCount,{quantity:quantityAfter(projectedCount.quantity,target.dataset.action)});}catch(error){message(error.message,true);return;}void run(()=>action(target,context),target.dataset.action==='retry').catch(()=>{});}
 function queuePatch(patch,redraw=false){try{const context=patchContext(patch);void run(async()=>{await savePatch(patch,context);if(redraw)await render();}).catch(()=>{});}catch(error){lastError=error;message(error.message,true);}}
 function input(event){const target=event.target;if(currentRoute.view==='counter'&&['title','notes'].includes(target.name))queuePatch({[target.name]:target.value});if(modal?.querySelector('#submission-form')?.contains(target)){const form=modal.querySelector('#submission-form'),listId=currentRoute.listId;const draft={contact:Object.fromEntries(['firstName','lastName','phone','email','companyName'].map(k=>[k,form.querySelector(`[name="${k}"]`).value])),message:form.querySelector('[name="message"]').value,selectedIds:[...form.querySelectorAll('[name="selected"]:checked')].map(n=>n.value)};void run(()=>gateway.saveSubmissionDraft(draft,listId)).catch(()=>{});}}
 function change(event){const target=event.target;if(target.name==='projectId'&&fieldDirectory){const root=target.closest('form')??modal,projectId=target.value;void run(()=>loadFields(root,projectId)).catch(()=>{});}if(currentRoute.view==='counter'&&target.name==='quantity')queuePatch({quantity:target.value},true);if(currentRoute.view==='counter'&&target.name==='varietyLabel'){const value=target.value;queuePatch({varietyLabel:value||null,...(value?{title:value}:{})});}if(['sound','haptic'].includes(target.name))feedback?.setPreferences({[target.name]:target.checked});}
 function key(event){if(event.repeat&&['Enter',' '].includes(event.key)&&['increment','decrement'].includes(document.activeElement?.dataset?.action)){event.preventDefault();return;}if(event.key==='Escape'){closeModal();const menu=document.querySelector('#tools-menu');if(menu)menu.hidden=true;}if(event.key==='Tab'&&modal){const focusable=[...modal.querySelectorAll('button,input,select,textarea,a[href]')].filter(n=>!n.disabled);const first=focusable[0],last=focusable.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last?.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first?.focus();}}}
 const tools=()=>{const menu=document.querySelector('#tools-menu');if(menu){menu.hidden=!menu.hidden;document.querySelector('#tools-trigger')?.setAttribute('aria-expanded',String(!menu.hidden));}};
 document.addEventListener('click',click);document.addEventListener('input',input);document.addEventListener('change',change);document.addEventListener('keydown',key);document.querySelector('#tools-trigger')?.addEventListener('click',tools);
 const unsubscribe=gateway.subscribe(event=>{if(event.reason==='identity-change'){renderVersion++;if(scopeName)scopeQueues.set(scopeName,{route:{...currentRoute},tasks:[...failedTasks]});closeModal();main.replaceChildren();pending=Promise.resolve();failedTasks.length=0;storageBlocked=false;lastError=null;failedTask=null;projectedCount=null;try{scopeName=scopeKey(gateway.getScope());}catch{scopeName=null;message('Cambio account…');return;}const saved=scopeQueues.get(scopeName);currentRoute=saved?.route??{view:'lists'};failedTasks.push(...(saved?.tasks??[]));scopeQueues.delete(scopeName);storageBlocked=failedTasks.length>0;const retry=document.querySelector('#retry-save');if(retry)retry.hidden=!storageBlocked;pending=render().then(()=>{if(storageBlocked){lastError=new CountsError('LOCAL_STORAGE_FAILED','Appunti sospesi di questo profilo: riprova il salvataggio');message(lastError.message,true);}else message('Profilo caricato');}).catch(e=>message(e.message,true));}else if(['external-change','refresh','sync-error'].includes(event.reason)&&!modal&&document.activeElement?.tagName!=='INPUT'&&document.activeElement?.tagName!=='TEXTAREA')void run(()=>render()).catch(()=>{});});
 const api={ready:run(async()=>{await render();if(currentRoute.view!=='lists')await checkpoint();}),whenIdle:()=>pending,async prepareExit(){await pending;if(lastError||storageBlocked)throw lastError;await checkpoint();},async prepareIdentityChange(){renderVersion++;main.replaceChildren();message('Cambio account…');await api.prepareExit();},async refresh(){await gateway.refresh();await render();},async destroy(){await pending;disposed=true;unsubscribe();closeModal();document.removeEventListener('click',click);document.removeEventListener('input',input);document.removeEventListener('change',change);document.removeEventListener('keydown',key);document.querySelector('#tools-trigger')?.removeEventListener('click',tools);}};
 return api;
}
