import {CATEGORY_LABELS,CountsError,summarizeCounts,patchCount,validateCountPatch,quantityAfter,countDetailLines} from './model.js?v=1.2.4';
import {scopeKey} from './store.js';
import {buildCountsUrl} from './navigation.js';
import {buildSubmission} from './submission.js?v=1.2.4';
import {counterView,icon} from './counter-view.js?v=1.2.4';
import {listRootstocksForSelection} from '../src/plant-catalog.js';
export const NOTICE_TEXT='I conteggi e le note sincronizzati sono conservati sui sistemi Vivai Obice e consultabili dagli amministratori autorizzati, anche senza una richiesta di fornitura. Il pulsante “Trasmetti a Vivai Obice” serve a sottoporci volontariamente un riepilogo come richiesta.';
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const states={local:'Salvato sul dispositivo',pending:'Sincronizzazione in attesa',synced:'Sincronizzato',error:'Salvato sul dispositivo · sincronizzazione da riprovare',conflict:'Conflitto da risolvere'};
const emails={pending:'Richiesta conservata · email in attesa',sending:'Richiesta conservata · invio email in corso',provider_accepted:'Richiesta conservata · email accettata dal servizio di invio',failed:'Richiesta conservata · invio email non riuscito',uncertain:'Richiesta conservata · esito email non confermato'};
const button=(action,label,extra='')=>`<button type="button" data-action="${action}" ${extra}>${label}</button>`;
export function mountCountsUI({document=globalThis.document,window=globalThis.window,gateway,route={view:'resume'},config={},fieldDirectory=null,pendingFieldContext=null,varietyCatalog=[],authService=null,admin=null,feedback,onProfile=null}){
 const main=document.querySelector('#counts-main'),status=document.querySelector('#counts-status');let currentRoute={...route},data=null,pending=Promise.resolve(),lastError=null,disposed=false,renderVersion=0,modal=null,restoreFocus=null,review=null,reviewEditable=true,failedTask=null,storageBlocked=false,projectedCount=null,scopeName=scopeKey(gateway.getScope());const failedTasks=[],scopeQueues=new Map(),archiveLists=new Map();
 const message=(value,error=false)=>{if(status){status.textContent=String(value??'').replace(/^VALIDATION_ERROR:\s*/,'');status.classList.toggle('error',error);status.setAttribute('role',error?'alert':'status');}};
 function park(owner,fn){if(!owner)return;if(owner===scopeName){failedTasks.push(fn);storageBlocked=true;lastError=new CountsError('LOCAL_STORAGE_FAILED','Lavoro sospeso: riprova il salvataggio di questo profilo');const retry=document.querySelector('#retry-save');if(retry)retry.hidden=false;}else{const saved=scopeQueues.get(owner)??{route:{view:'lists'},tasks:[]};saved.tasks.push(fn);scopeQueues.set(owner,saved);}}
 function run(fn,recovery=false){const owner=scopeName,epoch=gateway.getEpoch();const next=pending.catch(()=>{}).then(async()=>{if(owner!==scopeName||epoch!==gateway.getEpoch()){park(owner,fn);return;}if(storageBlocked&&!recovery){failedTasks.push(fn);return;}const value=await fn();if(lastError?.code==='VALIDATION_ERROR'){lastError=null;message('Salvato sul dispositivo');}return value;});pending=next.catch(error=>{if(owner!==scopeName||epoch!==gateway.getEpoch()){park(owner,fn);return;}if(['LOCAL_STORAGE_FAILED','VALIDATION_ERROR'].includes(error.code))lastError=error;failedTask=fn;if(error.code==='LOCAL_STORAGE_FAILED'){storageBlocked=true;if(!recovery)failedTasks.push(fn);}message(error.message||'Operazione non riuscita',true);const retry=document.querySelector('#retry-save');if(retry)retry.hidden=false;});return next;}
 function show(html){closeModal();restoreFocus=document.activeElement;modal=document.createElement('div');modal.className='counts-modal';if(data?.list?.listId)modal.dataset.listId=data.list.listId;if(data?.count?.countId)modal.dataset.countId=data.count.countId;modal.innerHTML=`<section role="dialog" aria-modal="true" aria-labelledby="dialog-title" class="dialog-card">${html}<div class="dialog-actions">${button('close-modal','Chiudi')}</div></section>`;document.body.append(modal);modal.querySelector('input,button,textarea,select')?.focus();}
 function closeModal(){modal?.remove();modal=null;restoreFocus?.focus?.();}
 let flashTimer;
 function flash(){const epoch=gateway.getEpoch();document.body.classList.remove('impulse-flash');window?.clearTimeout?.(flashTimer);window?.requestAnimationFrame?.(()=>{if(disposed||epoch!==gateway.getEpoch())return;document.body.classList.add('impulse-flash');flashTimer=window.setTimeout?.(()=>document.body.classList.remove('impulse-flash'),140);});}
 function materialFields(c){
  if(c.category==='plants')return `<div class="material-fields"><label>Vitigno<input name="varietyLabel" value="${esc(c.varietyLabel)}" maxlength="200" list="reading-varieties" placeholder="Facoltativo"></label><label>Portainnesto<input name="rootstockLabel" value="${esc(c.rootstockLabel)}" maxlength="200" list="reading-rootstocks" placeholder="Facoltativo"></label></div><datalist id="reading-varieties">${varietyCatalog.map(v=>`<option value="${esc(typeof v==='string'?v:v.label)}"></option>`).join('')}</datalist><datalist id="reading-rootstocks">${listRootstocksForSelection().map(v=>`<option value="${esc(v)}"></option>`).join('')}</datalist>`;
  const fields=c.category==='posts'?[['postType','Tipo palo',['testa','filare','altro']],['postMaterial','Materiale',['castagno','ferro','altro']]]:[['componentType','Componente',['molle','tendifili','ancore','fili','tutori','legacci','distanziatori','altro']]];
  return `<div class="material-fields">${fields.map(([name,label,choices])=>`<label>${label}<input name="${name}" value="${esc(c[name])}" maxlength="80" list="reading-${name}" placeholder="Scegli o scrivi altro"><datalist id="reading-${name}">${choices.map(value=>`<option value="${value}"></option>`).join('')}</datalist></label>`).join('')}</div><p class="material-hint">Scegli una proposta oppure scrivi un dettaglio diverso.</p>`;
 }
 async function detailsForm(){
  const c=data.count,epoch=gateway.getEpoch();const page=await gateway.listLists({limit:100}),lists=page.items;if(epoch!==gateway.getEpoch())throw new CountsError('AUTH_REQUIRED');projectedCount=structuredClone(c);
  show(`<h2 id="dialog-title">Dettagli lettura</h2><p class="eyebrow">${CATEGORY_LABELS[c.category]}</p><form id="reading-details" data-list-id="${c.listId}" data-count-id="${c.countId}"><label>Nome lettura<input name="title" value="${esc(c.title)}" maxlength="200" required></label><label>Quantità<input name="quantity" value="${c.quantity}" inputmode="numeric" pattern="[0-9]+" aria-label="Correggi quantità"></label>${materialFields(c)}<p class="field-label">${esc(c.field?.fieldLabel??'Senza campo')} ${button('change-field',icon('plants'),'class="icon-button" aria-label="Associa campo" title="Associa campo"')}</p><label>Note<textarea name="notes" rows="2" maxlength="10000">${esc(c.notes)}</textarea></label><input type="hidden" name="destinationListId" value="${c.listId}"><div class="destination-heading"><span>Elenco</span>${button('details-new-list',icon('pagePlus'),'class="icon-button" aria-label="Crea nuovo elenco" title="Crea nuovo elenco"')}</div><div class="destination-lists">${lists.map(l=>button('choose-destination',icon('archive')+`<span>${esc(l.title)}</span>`,`data-list-id="${l.listId}" aria-pressed="${l.listId===c.listId}"`)).join('')}</div>${page.nextCursor?button('more-destinations','Altri elenchi',`data-cursor="${page.nextCursor}"`):''}<div class="actions">${button('save-details',icon('save')+' Salva dettagli','class="primary"')}${button('resume-count','Riprendi il conteggio','class="resume"')}${button('delete-count',icon('reset'),'class="icon-button danger" aria-label="Elimina lettura"')}</div></form>`);
 }
 function progress(record){return `<span class="sync-state ${esc(record.syncState)}">${esc(states[record.syncState]??states.local)}</span>`;}
 async function checkpoint(){const route=structuredClone(currentRoute);await gateway.checkpoint(route);const restored=await gateway.resume();if(JSON.stringify(restored)!==JSON.stringify(route))throw new CountsError('LOCAL_STORAGE_FAILED','Ripristino non verificato');}
 async function go(next){await checkpoint();currentRoute={...next};await checkpoint();if(window?.history?.replaceState&&window.location)window.history.replaceState(null,'',buildCountsUrl(config.countsBaseUrl??new URL('./',window.location.href).href,currentRoute));await render();}
 function recordRows(counts,listId){return summarizeCounts(counts).map(group=>`<details class="archive-category" data-category="${group.category}"><summary><span>${icon(group.category)}${CATEGORY_LABELS[group.category]}</span><strong>${group.totalQuantity}</strong><span class="category-chevron" aria-hidden="true">⌄</span></summary><div class="count-rows">${group.items.length?group.items.map(c=>`<article class="count-row"><div><h4>${esc(c.title)}</h4><p class="field-label">${esc(c.field?(c.field.associationStatus==='unavailable'?'Campo non disponibile':c.field.fieldLabel):'Senza campo associato')}</p>${countDetailLines(c).length?`<p class="reading-material">${countDetailLines(c).map(esc).join(' · ')}</p>`:''}${progress(c)}${c.notes?`<p class="notes">${esc(c.notes)}</p>`:''}${c.conflict?conflictHTML('count',c):''}</div><strong>${c.quantity}</strong>${button('open-count',icon('edit'),`class="icon-button" aria-label="Modifica ${esc(c.title)}" data-list-id="${listId}" data-count-id="${c.countId}"`)}</article>`).join(''):'<p class="category-empty">Nessuna lettura in questa categoria.</p>'}</div></details>`).join('');}
 function archiveCard({list,counts,submissions}){const context=`data-list-id="${list.listId}"`;return `<article class="archive-list list-card" ${context}><header class="list-heading"><div><p class="eyebrow">${list.status==='closed'?'Elenco concluso':'Elenco aperto'} · ${esc(new Date(list.updatedAt).toLocaleDateString('it-IT'))}</p><h2>${esc(list.title)}</h2>${progress(list)}</div><div class="list-tools">${button('add-count',icon('plus'),`class="icon-button" aria-label="Nuova lettura in ${esc(list.title)}" title="Nuova lettura" ${context}`)}${button('rename-list',icon('edit'),`class="icon-button" aria-label="Rinomina ${esc(list.title)}" title="Rinomina elenco" ${context}`)}${button('toggle-list',icon(list.status==='closed'?'reset':'save'),`class="icon-button" aria-label="${list.status==='closed'?'Riapri':'Concludi'} ${esc(list.title)}" title="${list.status==='closed'?'Riapri elenco':'Concludi elenco'}" ${context}`)}${button('delete-list',icon('reset'),`class="icon-button danger" aria-label="Elimina ${esc(list.title)}" title="Elimina elenco" ${context}`)}</div></header>${recordRows(counts,list.listId)}${list.conflict?conflictHTML('list',list):''}<div class="archive-share">${button('review',icon('share')+'<span>Trasmetti a Vivai Obice</span>',`class="share-reading" ${context}`)}</div>${submissions.map(s=>`<details class="submission-record"><summary>Riepilogo trasmesso · ${esc(new Date(s.acceptedAt).toLocaleString('it-IT'))}</summary><p>${esc(emails[s.emailState]??emails.pending)}</p>${['pending','failed','uncertain','sending'].includes(s.emailState)?button('retry-submission','Riprova questa trasmissione',`data-id="${s.submissionId}" ${context}`):''}<p class="muted">Il ritentativo conserva lo stesso riepilogo e lo stesso identificatore.</p><h3>${esc(s.snapshot.listTitle)}</h3>${s.snapshot.entries.map(c=>`<p><b>${esc(c.title)} · ${c.quantity} ${CATEGORY_LABELS[c.category]}</b></p><p>${countDetailLines(c).map(esc).join(' · ')}</p><p class="notes">${esc(c.notes)}</p>`).join('')}<p class="notes">${esc(s.message)}</p><p class="muted">Uno strumento Vivai Obice</p></details>`).join('')}</article>`;}
 async function archiveView(isCurrent){
  const recovery=await gateway.listRecoveryProposals(),lists=[];let cursor;
  do{const page=await gateway.listLists({limit:100,...(cursor?{cursor}:{}),...(currentRoute.projectId?{projectId:currentRoute.projectId}:{}),...(currentRoute.fieldId?{fieldId:currentRoute.fieldId}:{})});if(!isCurrent())return '';lists.push(...page.items);cursor=page.nextCursor;}while(cursor);
  if(currentRoute.listId){const selected=lists.findIndex(l=>l.listId===currentRoute.listId);if(selected>0)lists.unshift(...lists.splice(selected,1));}
  const results=await Promise.all(lists.map(async l=>({...await gateway.getList(l.listId),submissions:await gateway.listSubmissions(l.listId)})));if(!isCurrent())return '';
  archiveLists.clear();for(const result of results)archiveLists.set(result.list.listId,result);data=results[0]??null;
  const resume=(await gateway.getReading())?{view:'new'}:await gateway.resume();if(!isCurrent())return '';
  return `<section class="intro archive-intro"><div><p class="eyebrow">Rimesse, pali e appunti di campo</p><h2>Le tue letture</h2><p>Tutti gli elenchi e i loro conteggi, qui.</p></div><div class="archive-create">${button('start',icon('plus'),'class="icon-button primary" aria-label="Nuova lettura" title="Nuova lettura"')}${button('create-list',icon('pagePlus'),'class="icon-button" aria-label="Nuovo elenco" title="Nuovo elenco"')}</div>${['new','counter'].includes(resume?.view)?button('resume','Riprendi il conteggio','class="resume archive-resume"'):''}</section><section class="list-grid archive-grid" aria-label="Elenchi di letture">${results.length?results.map(archiveCard).join(''):'<div class="empty"><h3>Un appunto alla volta.</h3><p>Inizia un conteggio o crea il tuo primo elenco.</p></div>'}</section>${recovery.length?`<section class="card"><h3>Proposte conservate</h3><p>Sono conservate qui le proposte eliminate sul server o divergenti durante un trasferimento. Puoi consultarle senza sovrascrivere i conteggi correnti.</p>${recovery.map(r=>`<h4>${esc(r.local.title)}</h4>${r.kind==='count'?`<p>Quantità: ${r.local.quantity}</p>`:''}<p class="notes">${esc(r.local.notes)}</p>`).join('')}</section>`:''}`;
 }
 async function fieldOptions(){
  if(!fieldDirectory)return `<p class="muted">Rubrica campi disponibile con connessione. Puoi conservare la lettura senza associazione.</p><input type="hidden" name="projectId" value=""><input type="hidden" name="fieldId" value="">`;
  const epoch=gateway.getEpoch();const projects=await fieldDirectory.listProjects().catch(()=>null);if(epoch!==gateway.getEpoch())throw new CountsError('AUTH_REQUIRED');
  return `<input type="hidden" name="projectId" value=""><input type="hidden" name="fieldId" value=""><div class="field-projects">${button('choose-field','Senza campo','data-project-id="" data-field-id="" aria-pressed="true"')}${projects?projects.map(p=>button('field-project',icon('archive')+`<span>${esc(p.projectLabel)}</span>`,`data-project-id="${esc(p.projectId)}"`)).join(''):'<p class="muted">Rubrica non disponibile con questa connessione.</p>'}</div><div id="field-choices" class="destination-lists"></div>`;
 }
 async function loadFields(root,projectId){
  const choices=root.querySelector('#field-choices');if(!choices)return;choices.innerHTML='';
  const epoch=gateway.getEpoch(),fields=await fieldDirectory.listFields(projectId).catch(()=>[]);if(epoch!==gateway.getEpoch())throw new CountsError('AUTH_REQUIRED');
  choices.innerHTML=fields.map(f=>button('choose-field',icon('plants')+`<span>${esc(f.fieldLabel)}</span>`,`data-project-id="${esc(projectId)}" data-field-id="${esc(f.fieldId)}" aria-pressed="false"`)).join('')||'<p class="muted">Nessun campo disponibile.</p>';
 }
 async function render(){const version=++renderVersion,epoch=gateway.getEpoch();const isCurrent=()=>version===renderVersion&&epoch===gateway.getEpoch()&&!disposed;lastError=null;failedTask=null;
  if(currentRoute.view==='resume'){const reading=await gateway.getReading(),saved=await gateway.resume();if(!isCurrent())return;currentRoute=reading?{view:'new'}:saved?.view==='counter'?saved:{view:'new'};}
  if(currentRoute.view==='new'){
   const scope=gateway.getScope(),existing=await gateway.getReading();if(!isCurrent())return;
   if(existing)data={count:existing};
   else {let field=null;
    if(currentRoute.projectId&&currentRoute.fieldId&&fieldDirectory)field=await fieldDirectory.resolveField(currentRoute.projectId,currentRoute.fieldId).catch(()=>null);
    else if(pendingFieldContext?.ownerId===scope.owner&&pendingFieldContext.environment===scope.environment)field={projectId:null,fieldId:null,projectLabel:pendingFieldContext.projectLabel,fieldLabel:pendingFieldContext.fieldLabel,varietyLabel:pendingFieldContext.varietyLabel,associationStatus:'pending',localRef:{localProjectId:pendingFieldContext.localProjectId,localFieldId:pendingFieldContext.localFieldId}};
    if(!isCurrent())return;const count=await gateway.startReading({listId:currentRoute.listId??null,field});if(!isCurrent())return;data={count};
   }
  }
  if(currentRoute.view==='counter'){try{data=await gateway.getList(currentRoute.listId);if(currentRoute.view==='counter')data.count=await gateway.getCount(currentRoute.listId,currentRoute.countId);}catch(error){if(version===renderVersion){message(error.message,true);main.innerHTML=`<section class="card"><h2>Conteggio non disponibile</h2><p>Verifica il profilo e, se attiva, la sincronizzazione. Puoi tornare alle tue liste.</p>${button('back','Le mie liste')}</section>`;}return;}}
  let html;
  if(['lists','list'].includes(currentRoute.view)){
   html=await archiveView(isCurrent);
  }else if(currentRoute.view==='new'){
   html=counterView(data.count,feedback);
  }else if(currentRoute.view==='counter'){
   html=counterView(data.count,feedback)+(data.count.conflict?conflictHTML('count',data.count):'');
  }else if(currentRoute.view==='admin'){
   if(!config.adminEnabled||!admin)html='<section class="card"><h2>Conteggi utenti</h2><p>Consultazione amministrativa non attivata.</p></section>';
   else html=`${button('back','← I miei conteggi')}<section class="card"><h2>Conteggi utenti</h2><p>Gli appunti sincronizzati sono distinti dalle richieste trasmesse volontariamente.</p><form id="admin-filter"><label>Proprietario<select name="ownerKind"><option value="">Tutti</option><option value="guest">Guest</option><option value="user">Registrati</option></select></label><label>Dal<input name="from" type="date"></label><label>Al<input name="to" type="date"></label><label>Stato lista<select name="listStatus"><option value="">Tutte</option><option value="open">Aperta</option><option value="closed">Conclusa</option></select></label><label>Richiesta trasmessa<select name="hasSubmission"><option value="">Tutte</option><option value="true">Sì</option><option value="false">No</option></select></label><div class="actions">${button('admin-notes','Appunti sincronizzati')}${button('admin-submissions','Richieste trasmesse')}</div></form><div id="admin-results"></div></section>`;
  }
  if(version!==renderVersion||disposed)return;document.body.classList.toggle('counter-mode',['new','counter'].includes(currentRoute.view));main.innerHTML=html??'';
  if(currentRoute.error)message(currentRoute.error,true);
  if(['new','counter'].includes(currentRoute.view)){projectedCount=structuredClone(data.count);message(states[data.count.syncState]??states.local);main.querySelector('[data-action="increment"]')?.focus();}else projectedCount=null;
 }
 function conflictHTML(kind,record){const remote=record.conflict?.remote;return `<aside class="conflict-panel"><h3>Due versioni da verificare</h3><p>La tua proposta è conservata.</p><h4>Su questo dispositivo</h4><p>${esc(record.title)}${kind==='count'?` · ${record.quantity}`:''}</p>${record.notes?`<p class="notes">${esc(record.notes)}</p>`:''}<h4>Versione ricevuta</h4>${remote?`<p>${esc(remote.title)}${kind==='count'?` · ${remote.quantity}`:''}${remote.deleted?' · eliminato':''}</p>${remote.notes?`<p class="notes">${esc(remote.notes)}</p>`:''}`:'<p>Versione non disponibile. Riprova la sincronizzazione.</p>'}${remote&&!remote.deleted?button('use-local','Mantieni la mia proposta',`data-kind="${kind}" data-id="${kind==='list'?record.listId:record.countId}"`):''}${remote?button('use-remote',remote.deleted?'Accetta eliminazione e conserva gli appunti':'Usa la versione ricevuta',`data-kind="${kind}" data-id="${kind==='list'?record.listId:record.countId}"`):''}${kind==='count'&&record.conflict?.code==='FIELD_UNAVAILABLE'?button('unassociate','Conserva senza associazione al campo',`data-kind="count" data-id="${record.countId}"`):''}</aside>`;}
 function patchContext(patch){const clean=validateCountPatch(patch),base=projectedCount??data.count;const context={owner:scopeName,route:{view:currentRoute.view==='new'?'new':'counter',listId:base.listId,countId:base.countId},operationId:crypto.randomUUID(),expectedLocalRevision:base.localRevision};projectedCount=patchCount(base,clean);return context;}
 async function savePatch(patch,context=patchContext(patch)){if(context.owner!==scopeName)throw new CountsError('AUTH_REQUIRED');const epoch=gateway.getEpoch(),{listId,countId}=context.route;if(context.route.view==='new'){context.input??={countId,operationId:context.operationId,expectedLocalRevision:context.expectedLocalRevision,patch};data.count=await gateway.updateReading(context.input);if(epoch!==gateway.getEpoch())throw new CountsError('AUTH_REQUIRED');message('Salvato sul dispositivo');return;}const current=context.current??=await gateway.getCount(listId,countId);context.input??={listId,countId,expectedRevision:current.revision,expectedLocalRevision:context.expectedLocalRevision,operationId:context.operationId,patch};try{const result=await gateway.updateCount(context.input);if(epoch!==gateway.getEpoch())throw new CountsError('AUTH_REQUIRED');data.count=await gateway.getCount(result.value.listId,countId);main.querySelector('#quantity-display')?.classList.remove('pulse');window?.requestAnimationFrame?.(()=>main.querySelector('#quantity-display')?.classList.add('pulse'));message(states[result.syncState]);}catch(error){if(error.code==='VERSION_CONFLICT'&&epoch===gateway.getEpoch()){const remote=current.conflict?.remote??error.details?.current??current;const proposal=patchCount(current,patch);data.count=await gateway.retainConflictProposal('count',countId,proposal,remote);await render();}throw error;}}
 function showFrozenReview(){const {snapshot,contact,message}=review;show(`<h2 id="dialog-title">Il riepilogo che trasmetterai</h2><p>Questo riepilogo è conservato. La trasmissione richiede una tua conferma.</p><h3>${esc(snapshot.listTitle)}</h3>${snapshot.entries.map(c=>`<p><b>${esc(c.title)} · ${c.quantity} ${CATEGORY_LABELS[c.category]}</b></p><p>${countDetailLines(c).map(esc).join(' · ')}</p><p class="notes">${esc(c.notes)}</p><p>${esc(c.field?.fieldLabel??'Senza campo')}</p>`).join('')}<p>${esc(contact.firstName)} ${esc(contact.lastName)} · ${esc(contact.email)} · ${esc(contact.phone)}</p><p class="notes">${esc(message)}</p><p>L’invio non costituisce un ordine.</p>${reviewEditable?button('edit-review','Modifica il riepilogo'):''}${button('send','Conferma e trasmetti','class="primary"')}`);}
 async function reviewForm(){const profile=authService?.getState?.()??{};const draft=await gateway.getSubmissionDraft(data.list.listId);if(draft?.review){review=draft.review;reviewEditable=!draft.attemptState||draft.attemptState==='rejected';showFrozenReview();return;}show(`<h2 id="dialog-title">Rivedi prima di trasmettere</h2><p>L’invio non costituisce un ordine.</p><form id="submission-form"><div class="review-rows">${data.counts.map(c=>`<label><input name="selected" type="checkbox" value="${c.countId}" ${!draft?.selectedIds||draft.selectedIds.includes(c.countId)?'checked':''}><span>${esc(c.title)} · ${c.quantity} ${CATEGORY_LABELS[c.category]}<small>${countDetailLines(c).map(esc).join(' · ')}</small><small class="notes">${esc(c.notes)}</small><small>${esc(c.field?.fieldLabel??'Senza campo')}</small></span></label>`).join('')}</div>${[['firstName','Nome','given-name'],['lastName','Cognome','family-name'],['phone','Telefono','tel'],['email','E-mail','email'],['companyName','Azienda (facoltativo)','organization']].map(([key,label,autocomplete])=>`<label>${label}<input name="${key}" type="${key==='email'?'email':key==='phone'?'tel':'text'}" autocomplete="${autocomplete}" value="${esc(draft?.contact?.[key]??profile[key]??'')}" ${key==='companyName'?'':'required'} maxlength="${key==='email'?254:key==='phone'?32:160}"></label>`).join('')}<label>Messaggio (facoltativo)<textarea name="message" maxlength="5000" rows="3">${esc(draft?.message??'')}</textarea></label><p><a href="https://www.vivaiobice.com/privacypolicy" target="_blank" rel="noopener">Informativa privacy</a></p>${button('freeze-review','Rivedi riepilogo','class="primary"')}</form>`);}
 async function adminResults(kind,cursor){const form=main.querySelector('#admin-filter');const input={};for(const key of ['ownerKind','from','to',...(kind==='notes'?['listStatus','hasSubmission']:[])]){const value=form.querySelector(`[name="${key}"]`)?.value;if(value)input[key]=key==='hasSubmission'?value==='true':key==='to'?value+'T23:59:59.999Z':value;}if(cursor)input.cursor=cursor;const epoch=gateway.getEpoch(),result=await (kind==='notes'?admin.listUserLists(input):admin.listSubmissions(input));if(epoch!==gateway.getEpoch())throw new CountsError('AUTH_REQUIRED');main.querySelector('#admin-results').innerHTML=`<h3>${kind==='notes'?'Appunti sincronizzati':'Richieste trasmesse'}</h3>${result.items.map(row=>`<article class="count-row"><div><h4>${esc(row.title??row.listTitle)}</h4><p>${row.owner.kind==='guest'?'Guest':'Registrato'} · ${esc(row.owner.technicalId)}</p><p>${esc(row.emailState?emails[row.emailState]:row.hasSubmission?'Richiesta presente':'Nessuna richiesta trasmessa')}</p></div>${button(kind==='notes'?'admin-open-list':'admin-open-submission','Consulta',`data-id="${row.listId??row.submissionId}"`)}</article>`).join('')||'<p>Nessun risultato.</p>'}${result.nextCursor?button('admin-more','Altri risultati',`data-kind="${kind}" data-cursor="${result.nextCursor}"`):''}`;}
 function actionContext(target){
  const name=target.dataset.action,form=modal?.querySelector('#reading-details');
  const listId=target.closest?.('.archive-list')?.dataset.listId??modal?.dataset.listId??currentRoute.listId;
  const selected=archiveLists.get(listId)??data;
  const context={owner:scopeName,route:{...currentRoute,...(listId?{listId}:{})},operationId:crypto.randomUUID(),listOperationId:crypto.randomUUID(),newListId:crypto.randomUUID(),newCountId:crypto.randomUUID(),listTitle:modal?.querySelector('[name="listTitle"]')?.value,expectedLocalRevision:name.includes('count')?data?.count?.localRevision:selected?.list?.localRevision};
  if(['increment','decrement','confirm-reset','confirm-count','resume-count','delete-count','confirm-delete-count','change-field','save-field','details-new-list','move-new-list'].includes(name)){context.route.countId=data?.count?.countId;context.expectedLocalRevision=data?.count?.localRevision;if(data?.count?.listId)context.route.listId=data.count.listId;}
  if(name==='open-count')context.route.countId=target.dataset.countId;
  if(name==='save-field')context.fieldSelection={projectId:modal.querySelector('[name="projectId"]').value,fieldId:modal.querySelector('[name="fieldId"]').value};
  if(name==='save-details'){context.details=Object.fromEntries(['title','quantity','varietyLabel','rootstockLabel','postType','postMaterial','componentType','notes','destinationListId'].flatMap(k=>{const node=form.querySelector(`[name="${k}"]`);return node?[[k,node.value]]:[];}));context.route={view:'counter',listId:form.dataset.listId,countId:form.dataset.countId};context.expectedLocalRevision=(projectedCount??data.count).localRevision;}
  if(name==='start')context.listTitle=`Conteggi del ${new Date().toLocaleDateString('it-IT')}`;
  return context;
 }
 async function action(target,context=actionContext(target)){if(context.owner!==scopeName)throw new CountsError('AUTH_REQUIRED');const epoch=gateway.getEpoch(),valid=()=>{if(epoch!==gateway.getEpoch())throw new CountsError('AUTH_REQUIRED');};const name=target.dataset.action;if(['add-count','rename-list','toggle-list','delete-list','review'].includes(name)&&archiveLists.has(context.route.listId))data=archiveLists.get(context.route.listId);
  if(name==='close-modal'){const details=Boolean(modal?.querySelector('#reading-details'));closeModal();if(details)await render();return;}
  if(name==='retry'){if(storageBlocked){while(failedTasks.length){await failedTasks[0]();failedTasks.shift();}storageBlocked=false;lastError=null;failedTask=null;}else if(failedTask){const retry=failedTask;lastError=null;failedTask=null;await retry();}message('Operazione completata');if(document.querySelector('#retry-save'))document.querySelector('#retry-save').hidden=true;return;}
  if(name==='start'){await go({view:'new'});return;}if(name==='create-list'){show(`<h2 id="dialog-title">Nuova lista</h2><label>Nome lista<input name="listTitle" maxlength="200" required></label>${button('save-new-list','Crea lista','class="primary"')}`);}
  if(name==='save-new-list'){const result=await gateway.createList({title:context.listTitle,listId:context.newListId,operationId:context.listOperationId});valid();closeModal();await go({view:'list',listId:result.value.listId});}
  if(name==='open-list')await go({view:'list',listId:target.dataset.listId});
  if(name==='open-count'){data=await gateway.getList(context.route.listId);valid();data.count=await gateway.getCount(context.route.listId,context.route.countId);valid();await detailsForm();}
  if(name==='resume'){const saved=(await gateway.getReading())?{view:'new'}:await gateway.resume();if(saved)await go(saved);}
  if(name==='back'){closeModal();await go({view:'lists'});}
  if(name==='to-list')await go({view:'list',listId:currentRoute.listId});
  if(name==='confirm-count'){if(context.route.view==='new'){const result=await gateway.finishReading({countId:context.route.countId,operationId:context.operationId});valid();await go({view:'list',listId:result.value.listId});}else await go({view:'list',listId:context.route.listId});message('Lettura salvata');}
  if(name==='reset')show(`<h2 id="dialog-title">Azzerare la lettura?</h2><p>Il conteggio torna a zero. Nome e dettagli restano conservati.</p>${button('confirm-reset','Azzera','class="danger"')}`);
  if(name==='confirm-reset'){if(context.route.view==='new')await gateway.changeReadingQuantity(context.route.countId,'set',0,context.operationId);else await gateway.changeQuantity(context.route.listId,context.route.countId,'set',0,context.operationId);valid();closeModal();await render();}
  if(name==='toggle-feedback'){const key=target.dataset.preference,prefs=feedback?.getPreferences?.()??{};feedback?.setPreferences?.({[key]:!prefs[key]});feedback?.prepare?.();await render();}
  if(name==='counter-menu')show(`<h2 id="dialog-title">Conteggi</h2><div class="menu-options">${button('back','Elenco letture')}${button('show-profile','Profilo')}${config.adminEnabled&&authService?.getState?.().isAdmin?button('show-admin','Conteggi utenti'):''}<a href="${esc(config.configuratorBaseUrl??'../')}" data-tool="configurator">Progetta impianto</a>${config.syncEnabled?button('notice','Sincronizzazione'):''}</div>`);
  if(name==='show-admin'){closeModal();await go({view:'admin'});}
  if(name==='show-profile'){closeModal();if(onProfile)onProfile();else document.querySelector('#profile-trigger')?.click();}
  if(name==='resume-count'){closeModal();await go({view:'counter',listId:context.route.listId,countId:context.route.countId});}
  if(name==='save-details'){const {destinationListId,...details}=context.details;const patch={...details,listId:destinationListId||context.route.listId};for(const key of ['varietyLabel','rootstockLabel','postType','postMaterial','componentType'])if(key in patch)patch[key]=patch[key]||null;await savePatch(patch,context);valid();closeModal();await go({view:'list',listId:patch.listId});}
  if(name==='more-destinations'){const page=await gateway.listLists({limit:100,cursor:target.dataset.cursor});valid();modal.querySelector('.destination-lists').insertAdjacentHTML('beforeend',page.items.map(l=>button('choose-destination',icon('archive')+`<span>${esc(l.title)}</span>`,`data-list-id="${l.listId}" aria-pressed="false"`)).join(''));if(page.nextCursor)target.dataset.cursor=page.nextCursor;else target.remove();}
  if(name==='choose-destination'){modal.querySelector('[name="destinationListId"]').value=target.dataset.listId;modal.querySelectorAll('[data-action="choose-destination"]').forEach(b=>b.setAttribute('aria-pressed',String(b===target)));}
  if(name==='details-new-list'){show(`<h2 id="dialog-title">Nuovo elenco</h2><label>Nome<input name="listTitle" maxlength="200" required></label>${button('move-new-list','Crea e sposta lettura','class="primary"')}`);}
  if(name==='move-new-list'){context.createdList??=await gateway.createList({title:context.listTitle,listId:context.newListId,operationId:context.listOperationId});valid();context.moveContext??={owner:context.owner,route:{view:'counter',listId:context.route.listId,countId:context.route.countId},expectedLocalRevision:context.expectedLocalRevision,operationId:context.operationId};await savePatch({listId:context.createdList.value.listId},context.moveContext);valid();closeModal();await go({view:'list',listId:context.createdList.value.listId});}
  if(name==='add-count')await go({view:'new',listId:context.route.listId});
  if(name==='increment'||name==='decrement'){const result=context.route.view==='new'?await gateway.changeReadingQuantity(context.route.countId,name,undefined,context.operationId):await gateway.changeQuantity(context.route.listId,context.route.countId,name,undefined,context.operationId);valid();if(data.count?.countId===context.route.countId){data.count=result.value;const output=main.querySelector('#quantity-display');if(output){output.textContent=data.count.quantity;output.style.setProperty('--digits',String(data.count.quantity).length);}const decrement=main.querySelector('[data-action="decrement"]');if(decrement)decrement.disabled=data.count.quantity===0;}feedback?.pulse(name);flash();message(states[result.syncState]);}
  if(name==='rename-list')show(`<h2 id="dialog-title">Rinomina lista</h2><label>Nome lista<input name="listTitle" value="${esc(data.list.title)}" maxlength="200" required></label>${button('save-list-title','Salva','class="primary"')}`);
  if(name==='save-list-title'||name==='toggle-list'){const l=data.list;context.updateInput??={listId:context.route.listId,expectedRevision:l.revision,expectedLocalRevision:context.expectedLocalRevision,operationId:context.operationId,patch:name==='toggle-list'?{status:l.status==='closed'?'open':'closed'}:{title:context.listTitle}};await gateway.updateList(context.updateInput);valid();closeModal();await render();}
  if(name==='delete-count'){await go({view:'counter',listId:context.route.listId,countId:context.route.countId});}
  if(name==='delete-list'||name==='delete-count')show(`<h2 id="dialog-title">Eliminare ${name==='delete-list'?'questa lista e i suoi conteggi':'questo conteggio'}?</h2><p>Conferma l’eliminazione.</p>${button(name==='delete-list'?'confirm-delete-list':'confirm-delete-count','Elimina','class="danger"')}`);
  if(name==='confirm-delete-list'){await gateway.deleteList(context.route.listId,context.expectedLocalRevision,context.operationId);valid();closeModal();await go({view:'lists'});}
  if(name==='confirm-delete-count'){await gateway.deleteCount(context.route.listId,context.route.countId,context.expectedLocalRevision,context.operationId);valid();closeModal();await go({view:'list',listId:context.route.listId});}
  if(name==='change-field'){const options=await fieldOptions();valid();show(`<h2 id="dialog-title">Associa a un campo</h2>${options}${button('save-field','Salva associazione')}`);}
  if(name==='field-project')await loadFields(modal,target.dataset.projectId);
  if(name==='choose-field'){modal.querySelector('[name="projectId"]').value=target.dataset.projectId;modal.querySelector('[name="fieldId"]').value=target.dataset.fieldId;modal.querySelectorAll('[data-action="choose-field"]').forEach(b=>b.setAttribute('aria-pressed',String(b===target)));}
  if(name==='save-field'){const {projectId,fieldId}=context.fieldSelection;const field=fieldId?await fieldDirectory.resolveField(projectId,fieldId):null;valid();if(fieldId&&!field)throw new CountsError('FIELD_UNAVAILABLE');context.fieldContext??={owner:context.owner,route:{view:'counter',listId:context.route.listId,countId:context.route.countId},expectedLocalRevision:context.expectedLocalRevision,operationId:context.operationId};await savePatch({field},context.fieldContext);valid();data=await gateway.getList(context.route.listId);data.count=await gateway.getCount(context.route.listId,context.route.countId);valid();closeModal();if(['list','lists'].includes(currentRoute.view))await detailsForm();else await render();}
  if(['use-local','use-remote','unassociate'].includes(name)){await gateway.resolveConflict(target.dataset.kind,target.dataset.id,name==='use-local'?'local':name==='unassociate'?'unassociate':'remote');valid();await render();}
  if(name==='sync'){await gateway.refresh();valid();await render();const sync=await gateway.getSyncStatus();valid();message(!sync.enabled?'Salvato sul dispositivo · sincronizzazione non attivata':!sync.acknowledged?'Salvato sul dispositivo · leggi l’avviso per sincronizzare':sync.conflicts?'Appunti salvati · conflitti da risolvere':sync.errors?'Appunti salvati · sincronizzazione da riprovare':sync.pending?'Appunti salvati · sincronizzazione in attesa':'Appunti sincronizzati');}
  if(name==='storage-info')show(`<h2 id="dialog-title">Salvataggio letture</h2><p>${esc(document.querySelector('#sync-banner')?.textContent||'Le letture sono salvate su questo dispositivo e restano legate al profilo e a questo browser.')}</p>${config.syncEnabled?button('notice','Avviso di sincronizzazione'):''}`);
  if(name==='notice')show(`<h2 id="dialog-title">Prima di sincronizzare</h2><p>${NOTICE_TEXT}</p><p>La sincronizzazione conserva gli appunti. La trasmissione di una richiesta richiede una tua scelta separata.</p><p><a href="https://www.vivaiobice.com/privacypolicy" target="_blank" rel="noopener">Informativa privacy</a></p>${button('accept-notice','Ho letto, attiva la sincronizzazione','class="primary"')}`);
  if(name==='accept-notice'){await gateway.acceptNotice(config.noticeVersion);closeModal();await gateway.refresh();await render();message('Sincronizzazione attivata');}
  if(name==='review'){if(!config.submitEnabled){show(`<h2 id="dialog-title">Trasmetti a Vivai Obice</h2><p>La trasmissione non è ancora attiva. Le letture restano salvate su questo dispositivo.</p>`);return;}await reviewForm();}
  if(name==='edit-review'){const draft=await gateway.getSubmissionDraft(context.route.listId);if(draft?.attemptState==='uncertain')throw new CountsError('VERSION_CONFLICT','L’esito è da verificare: ritenta lo stesso riepilogo');await gateway.saveSubmissionDraft({contact:draft?.contact??review.contact,message:draft?.message??review.message,selectedIds:draft?.selectedIds??review.snapshot.entries.map(c=>c.countId)},context.route.listId);await gateway.refresh();valid();data=await gateway.getList(context.route.listId);review=null;await reviewForm();}
  if(name==='freeze-review'){const form=modal.querySelector('#submission-form');if(form.reportValidity&&!form.reportValidity())return;context.draft??={contact:Object.fromEntries(['firstName','lastName','phone','email','companyName'].map(k=>[k,form.querySelector(`[name="${k}"]`).value.trim()])),message:form.querySelector('[name="message"]').value,selectedIds:[...form.querySelectorAll('[name="selected"]:checked')].map(n=>n.value)};const draft=context.draft;await gateway.saveSubmissionDraft(draft,context.route.listId);await gateway.sync();valid();const latest=await gateway.getList(context.route.listId);context.review??=buildSubmission({list:latest.list,counts:latest.counts.filter(c=>draft.selectedIds.includes(c.countId)),contact:draft.contact,message:draft.message,noticeVersion:config.noticeVersion});review=context.review;await gateway.saveSubmissionDraft({...draft,review},context.route.listId);valid();reviewEditable=true;showFrozenReview();}
  if(name==='send'){target.disabled=true;context.review??=structuredClone(review);try{await gateway.submit(context.review);valid();closeModal();await render();message('Riepilogo trasmesso e conservato');}catch(error){valid();const draft=await gateway.getSubmissionDraft(context.route.listId);reviewEditable=draft?.attemptState==='rejected';showFrozenReview();throw error;}finally{target.disabled=false;}}
  if(name==='retry-submission'){await gateway.retrySubmission(target.dataset.id);valid();await render();message('Ritentativo conservato con lo stesso riepilogo');}
  if(name==='admin-notes'||name==='admin-submissions')await adminResults(name==='admin-notes'?'notes':'submissions');
  if(name==='admin-more')await adminResults(target.dataset.kind,target.dataset.cursor);
  if(name==='admin-open-list'){const result=await admin.getUserList(target.dataset.id);valid();show(`<h2 id="dialog-title">Appunti sincronizzati</h2><h3>${esc(result.list.title)}</h3><p>${esc(result.owner.kind)} · ${esc(result.owner.technicalId)}</p>${result.counts.map(c=>`<p><b>${esc(c.title)} · ${c.quantity} ${CATEGORY_LABELS[c.category]}</b></p><p>${countDetailLines(c).map(esc).join(' · ')}</p><p class="notes">${esc(c.notes)}</p>`).join('')}`);}
  if(name==='admin-open-submission'){const s=await admin.getSubmission(target.dataset.id);valid();show(`<h2 id="dialog-title">Richiesta trasmessa volontariamente</h2><p>${esc(emails[s.emailState])}</p>${s.snapshot.entries.map(c=>`<p><b>${esc(c.title)} · ${c.quantity}</b></p><p class="notes">${esc(c.notes)}</p>`).join('')}<p>${esc(s.contact.firstName)} ${esc(s.contact.lastName)} · ${esc(s.contact.email)}</p><p class="notes">${esc(s.message)}</p>`);}
 }
 function click(event){const tool=event.target.closest?.('[data-tool]');if(tool){event.preventDefault();if(tool.dataset.tool==='counts'){document.querySelector('#tools-menu').hidden=true;return;}void run(async()=>{if(lastError||storageBlocked)throw lastError;await checkpoint();window.location.assign(config.configuratorBaseUrl);}).catch(()=>{});return;}const target=event.target.closest?.('[data-action]');if(!target||target.disabled)return;event.preventDefault();if(target.dataset.action==='category'){queuePatch({category:target.dataset.category},true);return;}if(target.dataset.action==='increment'||target.dataset.action==='decrement'){feedback?.prepare?.();}let context;try{context=actionContext(target);if(['increment','decrement'].includes(target.dataset.action)&&projectedCount)projectedCount=patchCount(projectedCount,{quantity:quantityAfter(projectedCount.quantity,target.dataset.action)});}catch(error){message(error.message,true);return;}const single=['confirm-count','save-details','save-field','move-new-list'].includes(target.dataset.action);if(single)target.disabled=true;void run(()=>action(target,context),target.dataset.action==='retry').catch(()=>{}).finally(()=>{if(single)target.disabled=false;});}
 function queuePatch(patch,redraw=false){try{const context=patchContext(patch);void run(async()=>{await savePatch(patch,context);if(redraw)await render();}).catch(()=>{});}catch(error){lastError=error;message(error.message,true);}}
 function input(event){const target=event.target;if(!modal&&['new','counter'].includes(currentRoute.view)&&target.name==='title')queuePatch({[target.name]:target.value});if(modal?.querySelector('#reading-details')?.contains(target)&&['title','quantity','notes','varietyLabel','rootstockLabel','postType','postMaterial','componentType'].includes(target.name)){queuePatch({[target.name]:['varietyLabel','rootstockLabel','postType','postMaterial','componentType'].includes(target.name)?target.value||null:target.value});}if(modal?.querySelector('#submission-form')?.contains(target)){const form=modal.querySelector('#submission-form'),listId=modal.dataset.listId;const draft={contact:Object.fromEntries(['firstName','lastName','phone','email','companyName'].map(k=>[k,form.querySelector(`[name="${k}"]`).value])),message:form.querySelector('[name="message"]').value,selectedIds:[...form.querySelectorAll('[name="selected"]:checked')].map(n=>n.value)};void run(()=>gateway.saveSubmissionDraft(draft,listId)).catch(()=>{});}}
 function change(event){const target=event.target;if(target.name==='projectId'&&fieldDirectory){const root=target.closest('form')??modal,projectId=target.value;void run(()=>loadFields(root,projectId)).catch(()=>{});}}
 function key(event){if(event.repeat&&['Enter',' '].includes(event.key)&&['increment','decrement'].includes(document.activeElement?.dataset?.action)){event.preventDefault();return;}if(event.key==='Escape'){closeModal();const menu=document.querySelector('#tools-menu');if(menu)menu.hidden=true;}if(event.key==='Tab'&&modal){const focusable=[...modal.querySelectorAll('button,input,select,textarea,a[href]')].filter(n=>!n.disabled);const first=focusable[0],last=focusable.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last?.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first?.focus();}}}
 const tools=()=>{const menu=document.querySelector('#tools-menu');if(menu){menu.hidden=!menu.hidden;document.querySelector('#tools-trigger')?.setAttribute('aria-expanded',String(!menu.hidden));}};
 document.addEventListener('click',click);document.addEventListener('input',input);document.addEventListener('change',change);document.addEventListener('keydown',key);document.querySelector('#tools-trigger')?.addEventListener('click',tools);
 const unsubscribe=gateway.subscribe(event=>{if(event.reason==='identity-change'){renderVersion++;if(scopeName)scopeQueues.set(scopeName,{route:{...currentRoute},tasks:[...failedTasks]});closeModal();main.replaceChildren();pending=Promise.resolve();failedTasks.length=0;storageBlocked=false;lastError=null;failedTask=null;projectedCount=null;try{scopeName=scopeKey(gateway.getScope());}catch{scopeName=null;message('Cambio account…');return;}const saved=scopeQueues.get(scopeName);currentRoute=saved?.route??{view:'resume'};failedTasks.push(...(saved?.tasks??[]));scopeQueues.delete(scopeName);storageBlocked=failedTasks.length>0;const retry=document.querySelector('#retry-save');if(retry)retry.hidden=!storageBlocked;pending=render().then(()=>{if(storageBlocked){lastError=new CountsError('LOCAL_STORAGE_FAILED','Appunti sospesi di questo profilo: riprova il salvataggio');message(lastError.message,true);}else message('Profilo caricato');}).catch(e=>message(e.message,true));}else if(['external-change','refresh','sync-error'].includes(event.reason)&&!modal&&document.activeElement?.tagName!=='INPUT'&&document.activeElement?.tagName!=='TEXTAREA')void run(()=>render()).catch(()=>{});});
 const api={ready:run(async()=>{const epoch=gateway.getEpoch();await render();if(epoch!==gateway.getEpoch())return;if(currentRoute.view!=='lists')await checkpoint();}),whenIdle:()=>pending,async prepareExit(){await pending;if(lastError||storageBlocked)throw lastError;await checkpoint();},async prepareIdentityChange(){await api.prepareExit();message('Cambio account…');},async refresh(){await gateway.refresh();await render();},async destroy(){await pending;disposed=true;unsubscribe();closeModal();document.removeEventListener('click',click);document.removeEventListener('input',input);document.removeEventListener('change',change);document.removeEventListener('keydown',key);document.querySelector('#tools-trigger')?.removeEventListener('click',tools);}};
 return api;
}
