import {createRequire} from 'node:module';import {createServer} from 'node:http';import {readFile,writeFile,mkdir} from 'node:fs/promises';import {resolve,extname} from 'node:path';import {fileURLToPath} from 'node:url';import assert from 'node:assert/strict';
const require=createRequire(import.meta.url),{chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright');
const root=resolve(fileURLToPath(new URL('../',import.meta.url))),assets=process.env.MAP_VISIBILITY_BROWSER_ASSETS??'/tmp/v126-browser-assets',output=process.env.COORDINATE_BROWSER_OUTPUT??'/tmp/v130-coordinate-browser';await mkdir(output,{recursive:true});
const harness=`<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="/maplibre.css"><link rel="stylesheet" href="/coordinates.css"><style>body{margin:0}#map{width:100vw;height:100dvh}.vertex-edit-handle{width:28px;height:28px;border-radius:50%;background:#183f28;color:white;border:2px solid white;touch-action:none}.vertex-add-handle{border-radius:50%;width:22px;height:22px}</style></head><body><div id="map"></div><script src="/maplibre.js"></script><script type="module">
import {initMap} from '/src/map.js';import {corridorPolygonFromLine} from '/src/geometry.js';
window.changes=0;window.replacements=0;window.geometry=[[8.12,44.7],[8.121,44.7],[8.121,44.701],[8.12,44.701],[8.12,44.7]];window.axis=[[8.1205,44.7001],[8.1205,44.7009]];
window.exclusions=[{id:'cut',type:'linear',widthM:1.5,sourceAxis:axis,passageGroupId:'p',geometry:corridorPolygonFromLine(...axis)}];
window.api=initMap({container:'map',allowPanWhileEditing:()=>window.innerWidth<500,onGeometryChange:g=>{window.geometry=g;changes++;},onExclusionChange:(id,g,meta)=>{window.exclusions=exclusions.map(item=>item.id===id?{...item,...meta,geometry:g}:item);},onExclusionsReplace:next=>{window.exclusions=next;replacements++;api.setExclusions(next);},onExclusionAdd:(g,meta)=>{window.exclusions.push({...meta,id:'new-'+exclusions.length,geometry:g});}});
api.whenEditorReady(()=>{api.setGeometry(geometry);api.setExclusions(exclusions);window.ready=true;});
</script></body></html>`;
const server=createServer(async(req,res)=>{try{const pathname=new URL(req.url,'http://localhost').pathname;res.setHeader('Content-Type',({'.js':'application/javascript','.html':'text/html','.css':'text/css'})[extname(pathname)]??'text/html');if(pathname==='/'){res.end(harness);return;}if(pathname==='/maplibre.js'){res.end(await readFile(resolve(assets,'maplibre-gl.js')));return;}if(pathname==='/maplibre.css'){res.end(await readFile(resolve(assets,'maplibre-gl.css')));return;}const path=resolve(root,'.'+pathname);if(!path.startsWith(root+'/'))throw Error('Forbidden');res.end(await readFile(path));}catch{res.writeHead(404);res.end();}});await new Promise(done=>server.listen(0,'127.0.0.1',done));const base='http://127.0.0.1:'+server.address().port;
let browser;const reports=[];
try{browser=await chromium.launch({headless:true,executablePath:process.env.COUNTS_CHROMIUM_PATH??'/tmp/v126-chrome/chromium',args:['--no-sandbox','--disable-dev-shm-usage']});for(const mobile of [false,true]){
const context=await browser.newContext(mobile?{viewport:{width:390,height:844},isMobile:true,hasTouch:true}:{viewport:{width:1200,height:900}}),page=await context.newPage(),errors=[],consoleErrors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')consoleErrors.push(m.text());});await page.route('**/*',route=>route.request().url().startsWith(base+'/')?route.continue():route.abort());
try{await page.goto(base);await page.waitForFunction(()=>window.ready);await page.evaluate(()=>api.beginVertexEditing());const tap=async locator=>mobile?locator.tap():locator.click();
const open=async()=>{await tap(page.locator('.vertex-edit-handle').first());await tap(page.locator('.vertex-coordinate-action'));await page.locator('.coordinate-dialog').waitFor();};
await open();await page.locator('.coordinate-dialog select').selectOption('EPSG:32632');await page.locator('.coordinate-dialog button[type=submit]').click();assert.equal(await page.evaluate(()=>changes),0);
await open();const inputs=page.locator('.coordinate-dialog input');await inputs.first().fill('8,12001');await inputs.last().fill('44,70001');await inputs.last().press('Enter');await page.waitForFunction(()=>changes===1);assert.deepEqual(await page.evaluate(()=>[geometry[0],geometry.at(-1)]),[[8.12001,44.70001],[8.12001,44.70001]]);
await open();await page.locator('.coordinate-dialog input').first().fill('8.1215');await page.locator('.coordinate-dialog input').last().fill('44.7005');await page.locator('.coordinate-dialog button[type=submit]').click();assert.ok((await page.locator('.coordinate-error').innerText()).length>0);assert.equal(await page.evaluate(()=>changes),1);await page.keyboard.press('Escape');assert.equal(await page.locator('.coordinate-dialog').count(),0);
await open();await page.evaluate(()=>{window.staleForm=document.querySelector('.coordinate-dialog form');api.stopTools();staleForm.dispatchEvent(new Event('submit',{cancelable:true}));});assert.equal(await page.locator('.coordinate-dialog').count(),0);assert.equal(await page.evaluate(()=>changes),1);
await page.evaluate(()=>api.beginVertexEditing());const box=await page.locator('.vertex-edit-handle').nth(1).boundingBox(),x=box.x+box.width/2,y=box.y+box.height/2;
if(mobile){const cdp=await context.newCDPSession(page);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x+25,y:y+10}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});}else{await page.mouse.move(x,y);await page.mouse.down();await page.mouse.move(x+25,y+10,{steps:10});await page.mouse.up();}await page.waitForFunction(()=>changes===2);assert.equal(await page.locator('.vertex-coordinate-action').count(),0);assert.equal(await page.locator('.coordinate-dialog').count(),0);
await page.evaluate(()=>api.beginExclusionEditing('cut'));await tap(page.locator('.passage-endpoint-handle').first());await tap(page.locator('.vertex-coordinate-action'));await page.locator('.coordinate-dialog input').first().fill('8.12052');await page.locator('.coordinate-dialog button[type=submit]').click();assert.equal(await page.evaluate(()=>replacements),1);assert.equal(await page.evaluate(()=>exclusions[0].widthM),1.5);assert.deepEqual(await page.evaluate(()=>exclusions[0].sourceAxis[0]),[8.12052,44.7001]);
await page.evaluate(()=>{api.stopTools();api.beginDraw();});for(const coordinate of [[8.1201,44.7001],[8.1208,44.7001],[8.1208,44.7008]]){const point=await page.evaluate(p=>{const q=api.map.project(p);return {x:q.x,y:q.y};},coordinate);if(mobile)await page.touchscreen.tap(point.x,point.y);else await page.mouse.click(point.x,point.y);}await page.evaluate(()=>api.finishDraw());assert.equal(await page.evaluate(()=>changes),3);assert.equal(await page.evaluate(()=>geometry.length),4);
await page.screenshot({path:resolve(output,(mobile?'mobile':'desktop')+'.png')});assert.deepEqual(errors,[]);reports.push({mode:mobile?'mobile':'desktop',passed:true,coordinateChanges:2,atomicPassageReplacements:1,manualDraw:true,dragPopupSuppressed:true});
}catch(error){await writeFile(resolve(output,(mobile?'mobile':'desktop')+'-failure.json'),JSON.stringify({errors,consoleErrors,state:await page.evaluate(()=>({api:!!window.api,map:!!window.api?.map,loaded:window.api?.map?.loaded(),ready:window.ready}))},null,2));await page.screenshot({path:resolve(output,(mobile?'mobile':'desktop')+'-failure.png')});throw error;}finally{await context.close();}
}await writeFile(resolve(output,'summary.json'),JSON.stringify({passed:true,reports},null,2));console.log(JSON.stringify({passed:true,reports}));}finally{await browser?.close();server.closeAllConnections();await new Promise(done=>server.close(done));}
