import {CountsError,id,keys,newList,newCount,patchCount,validateListPatch,quantityAfter,summarizeCounts} from '../conteggi/model.js';
import {createCountsStore,scopeKey} from '../conteggi/store.js';
const notFound=()=>{throw new CountsError('NOT_FOUND_OR_FORBIDDEN','Conteggio o lista non disponibile');};
const alive=(map,key)=>{const value=map[key];if(!value||value.deleted)notFound();return value;};
const stable=value=>JSON.stringify(value,(_,v)=>v&&typeof v==='object'&&!Array.isArray(v)?Object.fromEntries(Object.keys(v).sort().map(k=>[k,v[k]])):v);
export function createCountsGateway({store=createCountsStore(),scope,transport=null,channel=true}={}){
  scopeKey(scope);let current=structuredClone(scope),epoch=0,syncing=null,destroyed=false,paused=false;const listeners=new Set();
  const broadcast=channel&&globalThis.BroadcastChannel?new BroadcastChannel('vivai-obice-counts-v1'):null;
  const emit=(reason,extra={})=>{const event={scopeEpoch:epoch,reason,...extra};for(const fn of listeners)fn(event);broadcast?.postMessage({scope:scopeKey(current),event});};
  if(broadcast)broadcast.onmessage=e=>{if(e.data.scope===scopeKey(current))for(const fn of listeners)fn({...e.data.event,scopeEpoch:epoch,reason:'external-change'});};
  function activeScope(){if(paused)throw new CountsError('IDENTITY_UNRESOLVED','Cambio identità in corso');return current;}
  async function read(){const owner=activeScope(),version=epoch;const value=await store.read(owner);if(version!==epoch)throw new CountsError('AUTH_REQUIRED','Account cambiato');if(value.transferredTo)throw new CountsError('AUTH_REQUIRED','Questi appunti sono stati trasferiti. Accedi all’account che li ha ricevuti.');return value;}
  async function mutate(fn,reason='change'){const owner=activeScope(),version=epoch;const result=await store.mutate(owner,fn);if(version!==epoch)throw new CountsError('AUTH_REQUIRED','Account cambiato');if(!destroyed)emit(reason);return result;}
  function enqueue(state,kind,value,operationId){const entityId=kind==='list'?value.listId:value.countId;const pending=state.outbox.filter(op=>op.kind===kind&&op.entityId===entityId);const expectedRevision=pending.length?pending.at(-1).expectedRevision+1:value.revision;
    state.outbox.push({operationId,kind,entityId,expectedRevision,value:structuredClone(value),blocked:false});value.syncState=transport?'pending':'local';}
  function command(state,input,fn){id(input.operationId);const digest=stable(input);const previous=state.commands[input.operationId];if(previous){if(previous.digest!==digest)throw new CountsError('VALIDATION_ERROR','Identificatore operazione già usato con dati differenti');return previous.result;}const result=fn();state.commands[input.operationId]={digest,result:structuredClone(result)};return result;}
  function checkRevision(value,input){if(value.revision!==input.expectedRevision||value.localRevision!==input.expectedLocalRevision)throw new CountsError('VERSION_CONFLICT','Dati modificati: ricarica prima di salvare',{current:value});if(value.conflict)throw new CountsError('VERSION_CONFLICT','Risolvi prima il conflitto',{current:value});}
  const gateway={
    getScope:()=>structuredClone(activeScope()),getEpoch:()=>epoch,
    suspend(){paused=true;epoch++;emit('identity-change');},
    async setScope(next){scopeKey(next);if(scopeKey(next)===scopeKey(current)&&!paused)return;current=structuredClone(next);paused=false;epoch++;emit('identity-change');},
    async adoptGuestWork(proof){const target=activeScope(),v=epoch;if(proof?.targetOwnerId!==target.owner||proof.environment!==target.environment||!proof.sourceOwnerId)throw new CountsError('AUTH_REQUIRED');const result=await store.transfer({...target,owner:proof.sourceOwnerId},target);if(v!==epoch)throw new CountsError('AUTH_REQUIRED');emit('refresh');return result;},
    subscribe(fn){listeners.add(fn);return()=>listeners.delete(fn);},
    async listLists(filter={}){keys(filter,['projectId','fieldId','status','cursor','limit']);const state=await read();let items=Object.values(state.lists).filter(l=>!l.deleted&&(!filter.status||l.status===filter.status));if(filter.projectId||filter.fieldId){const ids=new Set(Object.values(state.counts).filter(c=>!c.deleted&&(!filter.projectId||c.field?.projectId===filter.projectId)&&(!filter.fieldId||c.field?.fieldId===filter.fieldId)).map(c=>c.listId));items=items.filter(l=>ids.has(l.listId));}items.sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)||a.listId.localeCompare(b.listId));const start=filter.cursor?items.findIndex(l=>l.listId===filter.cursor)+1:0,limit=Math.min(100,Math.max(1,filter.limit??50));const page=items.slice(start,start+limit);return {items:page,nextCursor:start+limit<items.length?page.at(-1).listId:null};},
    async listRecentLists(limit=5){return (await gateway.listLists({limit})).items;},
    async getList(listId){id(listId);const state=await read();return {list:alive(state.lists,listId),counts:Object.values(state.counts).filter(c=>!c.deleted&&c.listId===listId).sort((a,b)=>a.updatedAt.localeCompare(b.updatedAt))};},
    async getCount(listId,countId){id(listId);id(countId);const state=await read();alive(state.lists,listId);const count=alive(state.counts,countId);if(count.listId!==listId)notFound();return count;},
    async getFieldSummary(projectId,fieldId){id(projectId);const state=await read();const rows=Object.values(state.counts).filter(c=>!c.deleted&&!state.lists[c.listId]?.deleted&&c.field?.projectId===projectId&&c.field?.fieldId===fieldId);return {projectId,fieldId,categories:summarizeCounts(rows).map(group=>({...group,items:group.items.map(({countId,listId,title,quantity,revision,syncState})=>({countId,listId,title,quantity,revision,syncState}))})),updatedAt:rows.map(c=>c.updatedAt).sort().at(-1)??null};},
    async createList({title,operationId=crypto.randomUUID(),listId=crypto.randomUUID()}){return mutate(state=>command(state,{title,operationId,listId},()=>{if(state.lists[listId])throw new CountsError('VERSION_CONFLICT');const value=newList({listId,title});state.lists[listId]=value;enqueue(state,'list',value,operationId);return {value,operationId,syncState:value.syncState};}));},
    async createCount({operationId=crypto.randomUUID(),countId=crypto.randomUUID(),...input}){return mutate(state=>command(state,{...input,operationId,countId},()=>{alive(state.lists,input.listId);if(state.counts[countId])throw new CountsError('VERSION_CONFLICT');const value=newCount({...input,countId});state.counts[countId]=value;enqueue(state,'count',value,operationId);return {value,operationId,syncState:value.syncState};}));},
    async updateCount(input){keys(input,['listId','countId','expectedRevision','expectedLocalRevision','operationId','patch']);return mutate(state=>command(state,input,()=>{alive(state.lists,input.listId);const previous=alive(state.counts,input.countId);if(previous.listId!==input.listId)notFound();checkRevision(previous,input);const value=patchCount(previous,input.patch);alive(state.lists,value.listId);state.counts[input.countId]=value;enqueue(state,'count',value,input.operationId);return {value,operationId:input.operationId,syncState:value.syncState};}));},
    async getReading(){return (await read()).reading??null;},
    async hasLocalWork(){const state=await read();return Object.values(state.lists).some(l=>!l.deleted)||Boolean(state.reading&&(state.reading.localRevision>0||state.reading.field));},
    async startReading({listId=null,field=null,category='plants',title='Lettura'}={}){const existing=(await read()).reading;if(existing)return existing;return mutate(state=>{
      if(state.reading)return state.reading;
      if(listId)alive(state.lists,id(listId));
      const date=new Date(),day=[date.getFullYear(),date.getMonth()+1,date.getDate()].join('-');
      const value=newCount({countId:crypto.randomUUID(),listId:listId??crypto.randomUUID(),category,title,field});
      state.reading={...value,day,listTitle:`Letture del ${date.toLocaleDateString('it-IT')}`,destinationListId:listId};return state.reading;
    },'reading');},
    async updateReading({countId,expectedLocalRevision,operationId=crypto.randomUUID(),patch}){return mutate(state=>command(state,{countId,expectedLocalRevision,operationId,patch},()=>{
      keys(patch,['title','varietyLabel','rootstockLabel','category','quantity','notes','field']);const previous=state.reading;if(!previous||previous.countId!==id(countId))notFound();
      if(previous.localRevision!==expectedLocalRevision)throw new CountsError('VERSION_CONFLICT','La lettura è stata modificata in un’altra scheda');
      state.reading=patchCount(previous,patch);return state.reading;
    }),'reading');},
    async changeReadingQuantity(countId,action,value,operationId=crypto.randomUUID()){return mutate(state=>command(state,{countId,action,...(value!==undefined?{value}:{}),operationId},()=>{
      const previous=state.reading;if(!previous||previous.countId!==id(countId))notFound();
      state.reading=patchCount(previous,{quantity:quantityAfter(previous.quantity,action,value)});return {value:state.reading,syncState:'local'};
    }),'reading');},
    async finishReading({countId,listId=null,operationId=crypto.randomUUID()}){return mutate(state=>command(state,{countId,listId,operationId},()=>{
      const reading=state.reading;if(!reading||reading.countId!==id(countId))notFound();
      let destination=listId??reading.destinationListId;
      if(!listId&&destination&&(!state.lists[destination]||state.lists[destination].deleted))destination=null;
      if(!destination)destination=Object.values(state.lists).find(l=>!l.deleted&&l.status==='open'&&l.title===reading.listTitle)?.listId;
      if(destination)alive(state.lists,id(destination));
      else {destination=state.lists[reading.listId]?crypto.randomUUID():reading.listId;const list=newList({listId:destination,title:reading.listTitle});state.lists[destination]=list;enqueue(state,'list',list,crypto.randomUUID());}
      const {day,listTitle,destinationListId,...record}=reading;
      const value={...record,listId:destination};state.counts[value.countId]=value;enqueue(state,'count',value,operationId);
      state.reading=null;state.checkpoint={view:'list',listId:destination};return {value,syncState:value.syncState,operationId};
    }),'reading');},
    async updateList(input){keys(input,['listId','expectedRevision','expectedLocalRevision','operationId','patch']);return mutate(state=>command(state,input,()=>{const previous=alive(state.lists,input.listId);checkRevision(previous,input);const value={...previous,...validateListPatch(input.patch),localRevision:previous.localRevision+1,updatedAt:new Date().toISOString()};state.lists[input.listId]=value;enqueue(state,'list',value,input.operationId);return {value,operationId:input.operationId,syncState:value.syncState};}));},
    async changeQuantity(listId,countId,action,value,operationId=crypto.randomUUID()){return mutate(state=>command(state,{listId,countId,action,...(value!==undefined?{value}:{}),operationId},()=>{alive(state.lists,listId);const previous=alive(state.counts,countId);if(previous.listId!==listId)notFound();if(previous.conflict)throw new CountsError('VERSION_CONFLICT','Risolvi prima il conflitto');const next=patchCount(previous,{quantity:quantityAfter(previous.quantity,action,value)});state.counts[countId]=next;enqueue(state,'count',next,operationId);return {value:next,operationId,syncState:next.syncState};}));},
    async deleteCount(listId,countId,expectedLocalRevision,operationId=crypto.randomUUID()){return mutate(state=>command(state,{listId,countId,expectedLocalRevision,operationId},()=>{alive(state.lists,listId);const previous=alive(state.counts,countId);if(previous.listId!==listId)notFound();if(previous.localRevision!==expectedLocalRevision||previous.conflict)throw new CountsError('VERSION_CONFLICT');const value={...previous,deleted:true,localRevision:previous.localRevision+1,updatedAt:new Date().toISOString()};state.counts[countId]=value;enqueue(state,'count',value,operationId);return {value,operationId};}));},
    async deleteList(listId,expectedLocalRevision,operationId=crypto.randomUUID()){return mutate(state=>command(state,{listId,expectedLocalRevision,operationId},()=>{const list=alive(state.lists,listId);if(list.localRevision!==expectedLocalRevision||list.conflict)throw new CountsError('VERSION_CONFLICT');list.deleted=true;list.localRevision++;list.updatedAt=new Date().toISOString();enqueue(state,'list',list,operationId);for(const count of Object.values(state.counts).filter(c=>c.listId===listId&&!c.deleted)){count.deleted=true;count.localRevision++;enqueue(state,'count',count,crypto.randomUUID());}if(state.checkpoint?.listId===listId)state.checkpoint=null;return {value:list,operationId};}));},
    checkpoint:route=>mutate(state=>{state.checkpoint=structuredClone(route);return route;},'checkpoint'),
    async resume(){return (await read()).checkpoint;},
    async acceptNotice(version){if(!transport)throw new CountsError('SERVICE_DISABLED');const owner=activeScope(),v=epoch;await transport.request('notice',{version},owner);if(v!==epoch)throw new CountsError('AUTH_REQUIRED');await store.mutate(owner,state=>{state.notice=version;});emit('notice');},
    async hasNotice(){return Boolean((await read()).notice);},
    async getSyncStatus(){const state=await read();const rows=[...Object.values(state.lists),...Object.values(state.counts)];return {enabled:Boolean(transport),acknowledged:Boolean(state.notice),pending:state.outbox.length,conflicts:rows.filter(row=>row.conflict||row.syncState==='conflict').length,errors:rows.filter(row=>row.syncState==='error').length};},
    async sync(){if(paused)return;if(syncing)return syncing;const owner=current,v=epoch;syncing=(async()=>{if((await store.read(owner)).transferredTo)throw new CountsError('AUTH_REQUIRED','Appunti trasferiti: usa l’account destinatario.');if(!transport||!(await store.read(owner)).notice)return;
      while(v===epoch&&!destroyed){const state=await store.read(owner);if(state.transferredTo)throw new CountsError('AUTH_REQUIRED','Appunti trasferiti: usa l’account destinatario.');const op=state.outbox.find(o=>!o.blocked);if(!op)break;try{const response=await transport.request('mutate',op,owner);if(v!==epoch)return;
        await store.mutate(owner,s=>{s.outbox=s.outbox.filter(o=>o.operationId!==op.operationId);const map=op.kind==='list'?s.lists:s.counts;const local=map[op.entityId];if(!local)return;const later=s.outbox.some(o=>o.kind===op.kind&&o.entityId===op.entityId);if(local.conflict){local.revision=response.value.revision;local.syncState='conflict';local.conflict.remote=response.value;return;}const normalized=local.field&&stable(local.field)!==stable(response.value.field);map[op.entityId]=later?{...local,revision:response.value.revision,syncState:'pending'}:{...response.value,localRevision:local.localRevision+(normalized?1:0),syncState:'synced'};});emit('sync');
      }catch(error){if(v!==epoch)return;const terminal=['VERSION_CONFLICT','NOT_FOUND_OR_FORBIDDEN','FIELD_UNAVAILABLE','VALIDATION_ERROR'].includes(error.code);await store.mutate(owner,s=>{const map=op.kind==='list'?s.lists:s.counts;const local=map[op.entityId];if(terminal&&local){for(const queued of s.outbox)if(queued.kind===op.kind&&queued.entityId===op.entityId)queued.blocked=true;local.syncState='conflict';local.conflict={code:error.code,remote:error.details?.current??null,local:structuredClone(local)};}else if(local)local.syncState='error';});emit('sync-error');if(!terminal)break;}}
    })().finally(()=>{syncing=null;});return syncing;},
    async refresh(){await gateway.sync();const owner=activeScope(),v=epoch;if((await store.read(owner)).transferredTo)throw new CountsError('AUTH_REQUIRED','Appunti trasferiti: usa l’account destinatario.');if(!transport||!(await store.read(owner)).notice)return;let cursor;do{const response=await transport.request('pull',cursor?{cursor}:{},owner);if(v!==epoch)return;await store.mutate(owner,state=>{for(const [kind,map,rows]of [['list',state.lists,response.lists],['count',state.counts,response.counts]])for(const row of rows??[]){const entityId=kind==='list'?row.listId:row.countId;const local=map[entityId];if(state.outbox.some(op=>op.kind===kind&&op.entityId===entityId)||local?.conflict){if(row.deleted&&local){for(const op of state.outbox)if(op.kind===kind&&op.entityId===entityId)op.blocked=true;local.syncState='conflict';local.conflict={code:'VERSION_CONFLICT',local:local.conflict?.local??structuredClone(local),remote:row};}continue;}const changed=local&&(local.revision!==row.revision||stable({...local,localRevision:0,syncState:0})!==stable({...row,localRevision:0,syncState:0}));map[entityId]={...row,localRevision:(local?.localRevision??0)+(changed?1:0),syncState:'synced'};}for(const item of response.submissions??[])state.submissions[item.submissionId]={...state.submissions[item.submissionId],...item};});cursor=response.nextCursor;}while(cursor&&v===epoch);emit('refresh');},
    async retainConflictProposal(kind,entityId,proposal,remote){return mutate(state=>{const map=kind==='list'?state.lists:state.counts;const current=alive(map,entityId);const value={...proposal,revision:remote.revision,localRevision:current.localRevision+1,syncState:'conflict',conflict:{code:'VERSION_CONFLICT',remote,local:structuredClone(proposal)}};map[entityId]=value;for(const op of state.outbox)if(op.kind===kind&&op.entityId===entityId)op.blocked=true;return value;});},
    async resolveConflict(kind,entityId,choice){if(!['list','count'].includes(kind)||!['local','remote','unassociate'].includes(choice))throw new CountsError('VALIDATION_ERROR');return mutate(state=>{const map=kind==='list'?state.lists:state.counts,previous=map[entityId];if(choice==='unassociate'&&kind==='count'&&previous?.conflict?.code==='FIELD_UNAVAILABLE'){state.outbox=state.outbox.filter(o=>o.kind!==kind||o.entityId!==entityId);const value={...previous,field:null,localRevision:previous.localRevision+1};delete value.conflict;map[entityId]=value;enqueue(state,kind,value,crypto.randomUUID());return;}if(!previous?.conflict?.remote)throw new CountsError('VERSION_CONFLICT','Versione server non disponibile');const remote=previous.conflict.remote;if(choice==='local'&&remote.deleted)throw new CountsError('VERSION_CONFLICT','La voce eliminata sul server non può essere ripristinata automaticamente');state.outbox=state.outbox.filter(o=>o.kind!==kind||o.entityId!==entityId);if(remote.deleted){state.recoveryProposals??={};state.recoveryProposals[kind+':'+entityId]={kind,local:previous.conflict.local,remote};if(kind==='list'){for(const child of Object.values(state.counts).filter(c=>c.listId===entityId&&!c.deleted)){state.recoveryProposals['count:'+child.countId]={kind:'count',local:child.conflict?.local??structuredClone(child),remote:null};child.deleted=true;child.localRevision++;delete child.conflict;child.syncState='synced';}state.outbox=state.outbox.filter(o=>o.kind!=='count'||state.counts[o.entityId]?.listId!==entityId);if(state.checkpoint?.listId===entityId)state.checkpoint=null;}}const value=choice==='remote'?{...remote}:{...previous,revision:remote.revision};delete value.conflict;value.localRevision=previous.localRevision+1;value.syncState='synced';map[entityId]=value;if(choice==='local'||(!remote.deleted&&['local','pending','error'].includes(remote.syncState)))enqueue(state,kind,value,crypto.randomUUID());});},
    async listRecoveryProposals(){return Object.values((await read()).recoveryProposals??{});},
    async saveSubmissionDraft(draft,listId=draft?.review?.snapshot?.listId){return mutate(s=>{if(listId){s.submissionDrafts??={};s.submissionDrafts[listId]=draft;}else s.submissionDraft=draft;});},
    async getSubmissionDraft(listId){const state=await read();return listId?(state.submissionDrafts?.[listId]??null):state.submissionDraft;},
    async listSubmissions(listId){return Object.values((await read()).submissions).filter(s=>!listId||s.snapshot?.listId===listId);},
    async submit(input){if(!transport)throw new CountsError('SERVICE_DISABLED');const owner=activeScope(),v=epoch;await store.mutate(owner,s=>{s.submissionDrafts??={};const draft=s.submissionDrafts[input.snapshot.listId]??{};s.submissionDrafts[input.snapshot.listId]={...draft,review:structuredClone(input),attemptState:'uncertain'};});let response;try{response=await transport.submit(input,owner);}catch(error){if(v===epoch&&['VERSION_CONFLICT','VALIDATION_ERROR','NOT_FOUND_OR_FORBIDDEN'].includes(error.code))await store.mutate(owner,s=>{s.submissionDrafts[input.snapshot.listId].attemptState='rejected';});throw error;}if(v!==epoch)throw new CountsError('AUTH_REQUIRED');await store.mutate(owner,s=>{s.submissions[response.submissionId]={...response,request:structuredClone(input)};if(s.submissionDrafts)delete s.submissionDrafts[input.snapshot.listId];s.submissionDraft=null;});emit('submitted');return response;},
    async retrySubmission(submissionId){const state=await read();const entry=state.submissions[id(submissionId)];if(!entry)notFound();const request=entry.request??{submissionId:entry.submissionId,snapshot:entry.snapshot,contact:entry.contact,message:entry.message,noticeVersion:entry.noticeVersion};return gateway.submit(request);},
    async destroy(){destroyed=true;broadcast?.close();listeners.clear();}
  };return gateway;
}
export function createCountsTransport({client,environment}){
  async function invoke(name,body,scope){if(!scope?.owner)throw new CountsError('IDENTITY_UNRESOLVED');const session=(await client.auth.getSession())?.data?.session;if(!session?.access_token||session.user?.id!==scope.owner)throw new CountsError('AUTH_REQUIRED','Account cambiato: riprova nel profilo corretto');const {data,error}=await client.functions.invoke(name,{body:{...body,environment},headers:{Authorization:`Bearer ${session.access_token}`}});if(error){let payload;try{payload=await error.context?.json();}catch{}throw new CountsError(payload?.code??'SYNC_UNAVAILABLE',payload?.error??'Servizio temporaneamente non disponibile',payload?.details);}return data;}
  return {request:(action,input,scope)=>invoke('counts-api',{action,input},scope),submit:(input,scope)=>invoke('submit-counts',{input},scope),admin:(action,input,scope)=>invoke('counts-admin',{action,input},scope)};
}
export function createCountsAdmin({transport,getScope}){return {listUserLists:input=>transport.admin('listUserLists',input,getScope()),getUserList:listId=>transport.admin('getUserList',{listId},getScope()),listSubmissions:input=>transport.admin('listSubmissions',input,getScope()),getSubmission:submissionId=>transport.admin('getSubmission',{submissionId},getScope())};}
